<?php

namespace Database\Seeders;

use App\Models\User;
// use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DatabaseSeeder extends Seeder
{
    /**
     * Seed the application's database.
     */
    public function run(): void
    {
        // User::factory(10)->create();

        User::factory()->create([
            'name' => 'admin',
            'role' => 'admin',
            'phone' => '0909909900',
            'address' => '123 Bùi Văn Ba, Tân Thuận Đông, Q.7, tp.HCM',
            'status' => '0',
            'password' => '12345678',
            'email' => 'admin@vietstats.vn',
        ]);

        $indicators = [
            ['name' => 'Thu nhập và của cải', 'descriptions' => 'Thu nhập và của cải'],
            ['name' => 'Việc làm', 'descriptions' => 'Việc làm'],
            ['name' => 'Sức khỏe', 'descriptions' => 'Sức khỏe'],
            ['name' => 'Kiến thức và kỹ năng', 'descriptions' => 'Kiến thức và kỹ năng'],
            ['name' => 'Nhà ở và tiện nghi', 'descriptions' => 'Nhà ở và tiện nghi'],
            ['name' => 'Cảm nhận phúc lợi', 'descriptions' => 'Cảm nhận phúc lợi'],
            ['name' => 'Môi trường', 'descriptions' => 'Môi trường'],
            ['name' => 'An ninh, an toàn', 'descriptions' => 'An ninh, an toàn'],
            ['name' => 'Công việc và cuộc sống', 'descriptions' => 'Công việc và cuộc sống'],
            ['name' => 'Cố kết cộng đồng', 'descriptions' => 'Cố kết cộng đồng'],
            ['name' => 'Sự tham gia của người dân', 'descriptions' => 'Sự tham gia của người dân'],
            ['name' => 'Hành chính và quản trị công', 'descriptions' => 'Hành chính và quản trị công'],
        ];

        // Insert data into the 'weights' table
        DB::table('indicators')->insert($indicators);

        // Define the data to be seeded
        $weights = [
            ['name' => 'Thu nhập và của cải', 'value' => '20.0%', 'indicators_id' => 1],
            ['name' => 'Việc làm', 'value' => '12.0%', 'indicators_id' => 2],
            ['name' => 'Sức khỏe', 'value' => '12.0%', 'indicators_id' => 3],
            ['name' => 'Kiến thức và kỹ năng', 'value' => '12.0%', 'indicators_id' => 4],
            ['name' => 'Nhà ở và tiện nghi', 'value' => '7.0%', 'indicators_id' => 5],
            ['name' => 'Cảm nhận phúc lợi', 'value' => '7.0%', 'indicators_id' => 6],
            ['name' => 'Môi trường', 'value' => '5.0%', 'indicators_id' => 7],
            ['name' => 'An ninh, an toàn', 'value' => '5.0%', 'indicators_id' => 8],
            ['name' => 'Công việc và cuộc sống', 'value' => '5.0%', 'indicators_id' => 9],
            ['name' => 'Cố kết cộng đồng', 'value' => '5.0%', 'indicators_id' => 10],
            ['name' => 'Sự tham gia của người dân', 'value' => '5.0%', 'indicators_id' => 11],
            ['name' => 'Hành chính và quản trị công', 'value' => '5.0%', 'indicators_id' => 12],
        ];

        // Insert data into the 'weights' table
        DB::table('weights')->insert($weights);



        $questions = [
            ['question_code' => 'I.1a', 'title' => 'Mức độ hài lòng của ông/bà đối với thu nhập hiện tại của mình như thế nào?', 'indicator_id' => 1],
            ['question_code' => 'I.1b', 'title' => 'Cảm nhận về sự an tâm của ông/bà đối với của cải tích lũy nếu giả sử không may gặp rủi ro trong cuộc sống thế nào?', 'indicator_id' => 1],
            ['question_code' => 'I.2a', 'title' => 'Ông/bà đánh giá thế nào về sự ổn định trong công việc hiện tại của mình?', 'indicator_id' => 2],
            ['question_code' => 'I.2b', 'title' => 'Ông/bà đánh giá về mức độ tuân thủ của công ty đối với tiền lương và chính sách bảo hiểm cho người lao động như thế nào?', 'indicator_id' => 2],
            ['question_code' => 'I.2c', 'title' => 'Mức độ hài lòng của ông/bà đối với công việc hiện tại như thế nào?', 'indicator_id' => 2],
            ['question_code' => 'I.3a', 'title' => 'Mức độ hài lòng của ông/bà đối với chỗ ở hiện tại của mình như thế nào?', 'indicator_id' => 3],
            ['question_code' => 'I.3b', 'title' => 'Mức độ đáp ứng về chỗ ngủ cho tất cả các thành viên trong gia đình ông/bà như thế nào?', 'indicator_id' => 3],
            ['question_code' => 'I.3c', 'title' => 'Mức độ đáp ứng nhu cầu sống của các tiện nghi vật chất trong gia đình ông/bà thế nào (ví dụ như tivi, tủ lạnh, máy giặt, máy điều hòa…)?', 'indicator_id' => 3],
            ['question_code' => 'I.4a', 'title' => 'Mức độ hài lòng của ông/bà đối với chất lượng hoạt động chăm sóc sức khỏe và y tế ở địa phương mình thế nào (huyện/thị xã, thành phố)?', 'indicator_id' => 4],
            ['question_code' => 'I.4b', 'title' => 'Ông/bà tự nhận xét về tình trạng sức khỏe hiện tại của mình như thế nào?', 'indicator_id' => 4],
            ['question_code' => 'I.5a', 'title' => 'Ông/bà tự nhận xét về trình độ kiến thức, kỹ năng và kinh nghiệm của mình ở mức độ nào?', 'indicator_id' => 5],
            ['question_code' => 'I.5b', 'title' => 'Mức độ hài lòng của ông/bà đối với chất lượng giáo dục ở địa phương như thế nào?', 'indicator_id' => 5],
            ['question_code' => 'I.6a', 'title' => 'Ông/bà đánh giá chất lượng môi trường tự nhiên (không khí, nguồn nước) của địa phương mình như thế nào?', 'indicator_id' => 6],
            ['question_code' => 'I.6b', 'title' => 'Cảm nhận chung của ông/bà về môi trường sống ở địa phương thế nào?', 'indicator_id' => 6],
            ['question_code' => 'I.7a', 'title' => 'Mức độ hài lòng của ông/bà về phúc lợi hiện tại của mình và gia đình thế nào?', 'indicator_id' => 7],
            ['question_code' => 'I.7b', 'title' => 'Ông/bà đánh giá các chính sách phúc lợi của nhà nước đối với người dân địa phương tốt ở mức nào?', 'indicator_id' => 7],
            ['question_code' => 'I.8a', 'title' => 'Ông/bà đánh giá về mức độ an ninh ở địa phương như thế nào?', 'indicator_id' => 8],
            ['question_code' => 'I.8b', 'title' => 'Ông/bà cảm nhận thế nào về sự an toàn (tính mạng, tài sản) của mình ở địa phương?', 'indicator_id' => 8],
            ['question_code' => 'I.9a', 'title' => 'Ngoài công việc, ông/bà có thời gian dành cho việc nghỉ ngơi (thời gian riêng tư cho bản thân và gia đình) không?', 'indicator_id' => 9],
            ['question_code' => 'I.9b', 'title' => 'Ông/bà nhận thấy giữa công việc và cuộc sống của mình có thực sự cân bằng không?', 'indicator_id' => 9],
            ['question_code' => 'I.10a', 'title' => 'Ông/bà nhận thấy cộng đồng mình đang sống có đoàn kết, gắn bó tương trợ nhau tốt không?', 'indicator_id' => 10],
            ['question_code' => 'I.10b', 'title' => 'Trong tổ dân phố của mình đang sinh sống, ông/bà biết tên khoảng bao nhiêu % người trong tổ?', 'indicator_id' => 10],
            ['question_code' => 'I.11a', 'title' => 'Ông/bà thấy các ý kiến, kiến nghị của người dân được chính quyền tôn trọng, lắng nghe và tiếp thu như thế nào?', 'indicator_id' => 11],
            ['question_code' => 'I.11b', 'title' => 'Người dân địa phương có thường xuyên được tạo điều kiện tham gia vào các hoạt động của chính quyền địa phương (ví dụ như góp ý, giám sát) hoặc các hoạt động công cộng không?', 'indicator_id' => 11],
            ['question_code' => 'I.12a', 'title' => 'Ông/bà đánh giá về tính hiệu quả của chính quyền địa phương trong việc hỗ trợ người dân giải quyết việc làm và tăng thu nhập như thế nào?', 'indicator_id' => 12],
            ['question_code' => 'I.12b', 'title' => 'Ông/bà nhận thấy thế nào về mức độ quan tâm và hỗ trợ của chính quyền đối với đời sống của người dân ở địa phương?', 'indicator_id' => 12],
        ];

        foreach ($questions as $question) {
            DB::table('questions')->insert([
                'question_code' => $question['question_code'],
                'title' => $question['title'],
                'indicator_id' => $question['indicator_id'],
                'created_at' => now(),
                'updated_at' => now(),
            ]);
        }
        DB::table('regions')->insert([
            ['code' => 1, 'name' => 'Hà Nội', 'full_name' => 'Thành phố Hà Nội', 'full_name_en' => 'Ha Noi City'],
            ['code' => 26, 'name' => 'Vĩnh Phúc', 'full_name' => 'Tỉnh Vĩnh Phúc', 'full_name_en' => 'Vinh Phuc Province'],
            ['code' => 27, 'name' => 'Bắc Ninh', 'full_name' => 'Tỉnh Bắc Ninh', 'full_name_en' => 'Bac Ninh Province'],
            ['code' => 30, 'name' => 'Hải Dương', 'full_name' => 'Tỉnh Hải Dương', 'full_name_en' => 'Hai Duong Province'],
            ['code' => 31, 'name' => 'Hải Phòng', 'full_name' => 'Thành phố Hải Phòng', 'full_name_en' => 'Hai Phong City'],
            ['code' => 33, 'name' => 'Hưng Yên', 'full_name' => 'Tỉnh Hưng Yên', 'full_name_en' => 'Hung Yen Province'],
            ['code' => 34, 'name' => 'Thái Bình', 'full_name' => 'Tỉnh Thái Bình', 'full_name_en' => 'Thai Binh Province'],
            ['code' => 35, 'name' => 'Hà Nam', 'full_name' => 'Tỉnh Hà Nam', 'full_name_en' => 'Ha Nam Province'],
            ['code' => 96, 'name' => 'Cà Mau', 'full_name' => 'Tỉnh Cà Mau', 'full_name_en' => 'Ca Mau Province'],
            ['code' => 2, 'name' => 'Hà Giang', 'full_name' => 'Tỉnh Hà Giang', 'full_name_en' => 'Ha Giang Province'],
            ['code' => 4, 'name' => 'Cao Bằng', 'full_name' => 'Tỉnh Cao Bằng', 'full_name_en' => 'Cao Bang Province'],
            ['code' => 6, 'name' => 'Bắc Kạn', 'full_name' => 'Tỉnh Bắc Kạn', 'full_name_en' => 'Bac Kan Province'],
            ['code' => 8, 'name' => 'Tuyên Quang', 'full_name' => 'Tỉnh Tuyên Quang', 'full_name_en' => 'Tuyen Quang Province'],
            ['code' => 19, 'name' => 'Thái Nguyên', 'full_name' => 'Tỉnh Thái Nguyên', 'full_name_en' => 'Thai Nguyen Province'],
            ['code' => 20, 'name' => 'Lạng Sơn', 'full_name' => 'Tỉnh Lạng Sơn', 'full_name_en' => 'Lang Son Province'],
            ['code' => 22, 'name' => 'Quảng Ninh', 'full_name' => 'Tỉnh Quảng Ninh', 'full_name_en' => 'Quang Ninh Province'],
            ['code' => 24, 'name' => 'Bắc Giang', 'full_name' => 'Tỉnh Bắc Giang', 'full_name_en' => 'Bac Giang Province'],
            ['code' => 25, 'name' => 'Phú Thọ', 'full_name' => 'Tỉnh Phú Thọ', 'full_name_en' => 'Phu Tho Province'],
            ['code' => 10, 'name' => 'Lào Cai', 'full_name' => 'Tỉnh Lào Cai', 'full_name_en' => 'Lao Cai Province'],
            ['code' => 11, 'name' => 'Điện Biên', 'full_name' => 'Tỉnh Điện Biên', 'full_name_en' => 'Dien Bien Province'],
            ['code' => 12, 'name' => 'Lai Châu', 'full_name' => 'Tỉnh Lai Châu', 'full_name_en' => 'Lai Chau Province'],
            ['code' => 14, 'name' => 'Sơn La', 'full_name' => 'Tỉnh Sơn La', 'full_name_en' => 'Son La Province'],
            ['code' => 15, 'name' => 'Yên Bái', 'full_name' => 'Tỉnh Yên Bái', 'full_name_en' => 'Yen Bai Province'],
            ['code' => 17, 'name' => 'Hoà Bình', 'full_name' => 'Tỉnh Hoà Bình', 'full_name_en' => 'Hoa Binh Province'],
            ['code' => 70, 'name' => 'Bình Phước', 'full_name' => 'Tỉnh Bình Phước', 'full_name_en' => 'Binh Phuoc Province'],
            ['code' => 72, 'name' => 'Tây Ninh', 'full_name' => 'Tỉnh Tây Ninh', 'full_name_en' => 'Tay Ninh Province'],
            ['code' => 74, 'name' => 'Bình Dương', 'full_name' => 'Tỉnh Bình Dương', 'full_name_en' => 'Binh Duong Province'],
            ['code' => 75, 'name' => 'Đồng Nai', 'full_name' => 'Tỉnh Đồng Nai', 'full_name_en' => 'Dong Nai Province'],
            ['code' => 79, 'name' => 'Hồ Chí Minh', 'full_name' => 'Thành phố Hồ Chí Minh', 'full_name_en' => 'Ho Chi Minh City'],
            ['code' => 77, 'name' => 'Bà Rịa - Vũng Tàu', 'full_name' => 'Tỉnh Bà Rịa - Vũng Tàu', 'full_name_en' => 'Ba Ria - Vung Tau Province'],
            ['code' => 36, 'name' => 'Nam Định', 'full_name' => 'Tỉnh Nam Định', 'full_name_en' => 'Nam Dinh Province'],
            ['code' => 37, 'name' => 'Ninh Bình', 'full_name' => 'Tỉnh Ninh Bình', 'full_name_en' => 'Ninh Binh Province'],
            ['code' => 38, 'name' => 'Thanh Hóa', 'full_name' => 'Tỉnh Thanh Hóa', 'full_name_en' => 'Thanh Hoa Province'],
            ['code' => 40, 'name' => 'Nghệ An', 'full_name' => 'Tỉnh Nghệ An', 'full_name_en' => 'Nghe An Province'],
            ['code' => 42, 'name' => 'Hà Tĩnh', 'full_name' => 'Tỉnh Hà Tĩnh', 'full_name_en' => 'Ha Tinh Province'],
            ['code' => 44, 'name' => 'Quảng Bình', 'full_name' => 'Tỉnh Quảng Bình', 'full_name_en' => 'Quang Binh Province'],
            ['code' => 45, 'name' => 'Quảng Trị', 'full_name' => 'Tỉnh Quảng Trị', 'full_name_en' => 'Quang Tri Province'],
            ['code' => 46, 'name' => 'Thừa Thiên Huế', 'full_name' => 'Tỉnh Thừa Thiên Huế', 'full_name_en' => 'Thua Thien Hue Province'],
            ['code' => 48, 'name' => 'Đà Nẵng', 'full_name' => 'Thành phố Đà Nẵng', 'full_name_en' => 'Da Nang City'],
            ['code' => 49, 'name' => 'Quảng Nam', 'full_name' => 'Tỉnh Quảng Nam', 'full_name_en' => 'Quang Nam Province'],
            ['code' => 51, 'name' => 'Quảng Ngãi', 'full_name' => 'Tỉnh Quảng Ngãi', 'full_name_en' => 'Quang Ngai Province'],
            ['code' => 52, 'name' => 'Bình Định', 'full_name' => 'Tỉnh Bình Định', 'full_name_en' => 'Binh Dinh Province'],
            ['code' => 54, 'name' => 'Phú Yên', 'full_name' => 'Tỉnh Phú Yên', 'full_name_en' => 'Phu Yen Province'],
            ['code' => 56, 'name' => 'Khánh Hòa', 'full_name' => 'Tỉnh Khánh Hòa', 'full_name_en' => 'Khanh Hoa Province'],
            ['code' => 58, 'name' => 'Ninh Thuận', 'full_name' => 'Tỉnh Ninh Thuận', 'full_name_en' => 'Ninh Thuan Province'],
            ['code' => 60, 'name' => 'Bình Thuận', 'full_name' => 'Tỉnh Bình Thuận', 'full_name_en' => 'Binh Thuan Province'],
            ['code' => 62, 'name' => 'Kon Tum', 'full_name' => 'Tỉnh Kon Tum', 'full_name_en' => 'Kon Tum Province'],
            ['code' => 64, 'name' => 'Gia Lai', 'full_name' => 'Tỉnh Gia Lai', 'full_name_en' => 'Gia Lai Province'],
            ['code' => 66, 'name' => 'Đắk Lắk', 'full_name' => 'Tỉnh Đắk Lắk', 'full_name_en' => 'Dak Lak Province'],
            ['code' => 67, 'name' => 'Đắk Nông', 'full_name' => 'Tỉnh Đắk Nông', 'full_name_en' => 'Dak Nong Province'],
            ['code' => 68, 'name' => 'Lâm Đồng', 'full_name' => 'Tỉnh Lâm Đồng', 'full_name_en' => 'Lam Dong Province'],
            ['code' => 80, 'name' => 'Long An', 'full_name' => 'Tỉnh Long An', 'full_name_en' => 'Long An Province'],
            ['code' => 82, 'name' => 'Tiền Giang', 'full_name' => 'Tỉnh Tiền Giang', 'full_name_en' => 'Tien Giang Province'],
            ['code' => 83, 'name' => 'Bến Tre', 'full_name' => 'Tỉnh Bến Tre', 'full_name_en' => 'Ben Tre Province'],
            ['code' => 84, 'name' => 'Trà Vinh', 'full_name' => 'Tỉnh Trà Vinh', 'full_name_en' => 'Tra Vinh Province'],
            ['code' => 86, 'name' => 'Vĩnh Long', 'full_name' => 'Tỉnh Vĩnh Long', 'full_name_en' => 'Vinh Long Province'],
            ['code' => 87, 'name' => 'Đồng Tháp', 'full_name' => 'Tỉnh Đồng Tháp', 'full_name_en' => 'Dong Thap Province'],
            ['code' => 89, 'name' => 'An Giang', 'full_name' => 'Tỉnh An Giang', 'full_name_en' => 'An Giang Province'],
            ['code' => 91, 'name' => 'Kiên Giang', 'full_name' => 'Tỉnh Kiên Giang', 'full_name_en' => 'Kien Giang Province'],
            ['code' => 92, 'name' => 'Cần Thơ', 'full_name' => 'Thành phố Cần Thơ', 'full_name_en' => 'Can Tho City'],
            ['code' => 93, 'name' => 'Hậu Giang', 'full_name' => 'Tỉnh Hậu Giang', 'full_name_en' => 'Hau Giang Province'],
            ['code' => 94, 'name' => 'Sóc Trăng', 'full_name' => 'Tỉnh Sóc Trăng', 'full_name_en' => 'Soc Trang Province'],
            ['code' => 95, 'name' => 'Bạc Liêu', 'full_name' => 'Tỉnh Bạc Liêu', 'full_name_en' => 'Bac Lieu Province'],
        ]);

        DB::table('districts')->insert([
            ['name' => 'Ba Đình', 'full_name' => 'Quận Ba Đình', 'full_name_en' => 'Ba Dinh District', 'regions_code' => 1],
            ['name' => 'Hoàn Kiếm', 'full_name' => 'Quận Hoàn Kiếm', 'full_name_en' => 'Hoan Kiem District', 'regions_code' => 1],
            ['name' => 'Tây Hồ', 'full_name' => 'Quận Tây Hồ', 'full_name_en' => 'Tay Ho District', 'regions_code' => 1],
            ['name' => 'Long Biên', 'full_name' => 'Quận Long Biên', 'full_name_en' => 'Long Bien District', 'regions_code' => 1],
            ['name' => 'Cầu Giấy', 'full_name' => 'Quận Cầu Giấy', 'full_name_en' => 'Cau Giay District', 'regions_code' => 1],
            ['name' => 'Đống Đa', 'full_name' => 'Quận Đống Đa', 'full_name_en' => 'Dong Da District', 'regions_code' => 1],
            ['name' => 'Hai Bà Trưng', 'full_name' => 'Quận Hai Bà Trưng', 'full_name_en' => 'Hai Ba Trung District', 'regions_code' => 1],
            ['name' => 'Hoàng Mai', 'full_name' => 'Quận Hoàng Mai', 'full_name_en' => 'Hoang Mai District', 'regions_code' => 1],
            ['name' => 'Thanh Xuân', 'full_name' => 'Quận Thanh Xuân', 'full_name_en' => 'Thanh Xuan District', 'regions_code' => 1],
            ['name' => 'Sóc Sơn', 'full_name' => 'Huyện Sóc Sơn', 'full_name_en' => 'Soc Son District', 'regions_code' => 1],
            ['name' => 'Đông Anh', 'full_name' => 'Huyện Đông Anh', 'full_name_en' => 'Dong Anh District', 'regions_code' => 1],
            ['name' => 'Gia Lâm', 'full_name' => 'Huyện Gia Lâm', 'full_name_en' => 'Gia Lam District', 'regions_code' => 1],
            ['name' => 'Nam Từ Liêm', 'full_name' => 'Quận Nam Từ Liêm', 'full_name_en' => 'Nam Tu Liem District', 'regions_code' => 1],
            ['name' => 'Thanh Trì', 'full_name' => 'Huyện Thanh Trì', 'full_name_en' => 'Thanh Tri District', 'regions_code' => 1],
            ['name' => 'Bắc Từ Liêm', 'full_name' => 'Quận Bắc Từ Liêm', 'full_name_en' => 'Bac Tu Liem District', 'regions_code' => 1],
            ['name' => 'Mê Linh', 'full_name' => 'Huyện Mê Linh', 'full_name_en' => 'Me Linh District', 'regions_code' => 1],

            // Thêm huyện cho Vĩnh Phúc (regions_code = 26)
            ['name' => 'Vĩnh Yên', 'full_name' => 'Thành phố Vĩnh Yên', 'full_name_en' => 'Vinh Yen City', 'regions_code' => 26],
            ['name' => 'Phúc Yên', 'full_name' => 'Thành phố Phúc Yên', 'full_name_en' => 'Phuc Yen City', 'regions_code' => 26],
            ['name' => 'Lập Thạch', 'full_name' => 'Huyện Lập Thạch', 'full_name_en' => 'Lap Thach District', 'regions_code' => 26],
            ['name' => 'Tam Dương', 'full_name' => 'Huyện Tam Dương', 'full_name_en' => 'Tam Duong District', 'regions_code' => 26],
            ['name' => 'Tam Đảo', 'full_name' => 'Huyện Tam Đảo', 'full_name_en' => 'Tam Dao District', 'regions_code' => 26],
            ['name' => 'Bình Xuyên', 'full_name' => 'Huyện Bình Xuyên', 'full_name_en' => 'Binh Xuyen District', 'regions_code' => 26],
            ['name' => 'Yên Lạc', 'full_name' => 'Huyện Yên Lạc', 'full_name_en' => 'Yen Lac District', 'regions_code' => 26],
            ['name' => 'Vĩnh Tường', 'full_name' => 'Huyện Vĩnh Tường', 'full_name_en' => 'Vinh Tuong District', 'regions_code' => 26],
            ['name' => 'Sông Lô', 'full_name' => 'Huyện Sông Lô', 'full_name_en' => 'Song Lo District', 'regions_code' => 26],

            // Thêm huyện cho Bắc Ninh (regions_code = 27)
            ['name' => 'Bắc Ninh', 'full_name' => 'Thành phố Bắc Ninh', 'full_name_en' => 'Bac Ninh City', 'regions_code' => 27],
            ['name' => 'Từ Sơn', 'full_name' => 'Thị xã Từ Sơn', 'full_name_en' => 'Tu Son Town', 'regions_code' => 27],
            ['name' => 'Yên Phong', 'full_name' => 'Huyện Yên Phong', 'full_name_en' => 'Yen Phong District', 'regions_code' => 27],
            ['name' => 'Quế Võ', 'full_name' => 'Huyện Quế Võ', 'full_name_en' => 'Que Vo District', 'regions_code' => 27],
            ['name' => 'Tiên Du', 'full_name' => 'Huyện Tiên Du', 'full_name_en' => 'Tien Du District', 'regions_code' => 27],
            ['name' => 'Thuận Thành', 'full_name' => 'Huyện Thuận Thành', 'full_name_en' => 'Thuan Thanh District', 'regions_code' => 27],
            ['name' => 'Gia Bình', 'full_name' => 'Huyện Gia Bình', 'full_name_en' => 'Gia Binh District', 'regions_code' => 27],
            ['name' => 'Lương Tài', 'full_name' => 'Huyện Lương Tài', 'full_name_en' => 'Luong Tai District', 'regions_code' => 27],

            // Thêm huyện cho Hải Dương (regions_code = 30)
            ['name' => 'Hải Dương', 'full_name' => 'Thành phố Hải Dương', 'full_name_en' => 'Hai Duong City', 'regions_code' => 30],
            ['name' => 'Chí Linh', 'full_name' => 'Thị xã Chí Linh', 'full_name_en' => 'Chi Linh Town', 'regions_code' => 30],
            ['name' => 'Nam Sách', 'full_name' => 'Huyện Nam Sách', 'full_name_en' => 'Nam Sach District', 'regions_code' => 30],
            ['name' => 'Kinh Môn', 'full_name' => 'Huyện Kinh Môn', 'full_name_en' => 'Kinh Mon District', 'regions_code' => 30],
            ['name' => 'Kim Thành', 'full_name' => 'Huyện Kim Thành', 'full_name_en' => 'Kim Thanh District', 'regions_code' => 30],
            ['name' => 'Thanh Hà', 'full_name' => 'Huyện Thanh Hà', 'full_name_en' => 'Thanh Ha District', 'regions_code' => 30],
            ['name' => 'Cẩm Giàng', 'full_name' => 'Huyện Cẩm Giàng', 'full_name_en' => 'Cam Giang District', 'regions_code' => 30],
            ['name' => 'Bình Giang', 'full_name' => 'Huyện Bình Giang', 'full_name_en' => 'Binh Giang District', 'regions_code' => 30],
            ['name' => 'Gia Lộc', 'full_name' => 'Huyện Gia Lộc', 'full_name_en' => 'Gia Loc District', 'regions_code' => 30],
            ['name' => 'Tứ Kỳ', 'full_name' => 'Huyện Tứ Kỳ', 'full_name_en' => 'Tu Ky District', 'regions_code' => 30],
            ['name' => 'Ninh Giang', 'full_name' => 'Huyện Ninh Giang', 'full_name_en' => 'Ninh Giang District', 'regions_code' => 30],
            ['name' => 'Thanh Miện', 'full_name' => 'Huyện Thanh Miện', 'full_name_en' => 'Thanh Mien District', 'regions_code' => 30],

            // Thêm huyện cho Hải Phòng (regions_code = 31)
            ['name' => 'Hồng Bàng', 'full_name' => 'Quận Hồng Bàng', 'full_name_en' => 'Hong Bang District', 'regions_code' => 31],
            ['name' => 'Ngô Quyền', 'full_name' => 'Quận Ngô Quyền', 'full_name_en' => 'Ngo Quyen District', 'regions_code' => 31],
            ['name' => 'Lê Chân', 'full_name' => 'Quận Lê Chân', 'full_name_en' => 'Le Chan District', 'regions_code' => 31],
            ['name' => 'Hải An', 'full_name' => 'Quận Hải An', 'full_name_en' => 'Hai An District', 'regions_code' => 31],
            ['name' => 'Kiến An', 'full_name' => 'Quận Kiến An', 'full_name_en' => 'Kien An District', 'regions_code' => 31],
            ['name' => 'Đồ Sơn', 'full_name' => 'Quận Đồ Sơn', 'full_name_en' => 'Do Son District', 'regions_code' => 31],
            ['name' => 'Dương Kinh', 'full_name' => 'Quận Dương Kinh', 'full_name_en' => 'Duong Kinh District', 'regions_code' => 31],
            ['name' => 'Thủy Nguyên', 'full_name' => 'Huyện Thủy Nguyên', 'full_name_en' => 'Thuy Nguyen District', 'regions_code' => 31],
            ['name' => 'An Dương', 'full_name' => 'Huyện An Dương', 'full_name_en' => 'An Duong District', 'regions_code' => 31],
            ['name' => 'An Lão', 'full_name' => 'Huyện An Lão', 'full_name_en' => 'An Lao District', 'regions_code' => 31],
            ['name' => 'Kiến Thụy', 'full_name' => 'Huyện Kiến Thụy', 'full_name_en' => 'Kien Thuy District', 'regions_code' => 31],
            ['name' => 'Tiên Lãng', 'full_name' => 'Huyện Tiên Lãng', 'full_name_en' => 'Tien Lang District', 'regions_code' => 31],
            ['name' => 'Vĩnh Bảo', 'full_name' => 'Huyện Vĩnh Bảo', 'full_name_en' => 'Vinh Bao District', 'regions_code' => 31],
            ['name' => 'Cát Hải', 'full_name' => 'Huyện Cát Hải', 'full_name_en' => 'Cat Hai District', 'regions_code' => 31],
            ['name' => 'Bạch Long Vĩ', 'full_name' => 'Huyện Bạch Long Vĩ', 'full_name_en' => 'Bach Long Vi District', 'regions_code' => 31],

            // Các huyện của Hưng Yên
            ['name' => 'Hưng Yên', 'full_name' => 'Thành phố Hưng Yên', 'full_name_en' => 'Hung Yen City', 'regions_code' => 33],
            ['name' => 'Mỹ Hào', 'full_name' => 'Thị xã Mỹ Hào', 'full_name_en' => 'My Hao Town', 'regions_code' => 33],
            ['name' => 'Ân Thi', 'full_name' => 'Huyện Ân Thi', 'full_name_en' => 'An Thi District', 'regions_code' => 33],
            ['name' => 'Khoái Châu', 'full_name' => 'Huyện Khoái Châu', 'full_name_en' => 'Khoai Chau District', 'regions_code' => 33],
            ['name' => 'Kim Động', 'full_name' => 'Huyện Kim Động', 'full_name_en' => 'Kim Dong District', 'regions_code' => 33],
            ['name' => 'Phù Cừ', 'full_name' => 'Huyện Phù Cừ', 'full_name_en' => 'Phu Cu District', 'regions_code' => 33],
            ['name' => 'Tiên Lữ', 'full_name' => 'Huyện Tiên Lữ', 'full_name_en' => 'Tien Lu District', 'regions_code' => 33],
            ['name' => 'Văn Giang', 'full_name' => 'Huyện Văn Giang', 'full_name_en' => 'Van Giang District', 'regions_code' => 33],
            ['name' => 'Văn Lâm', 'full_name' => 'Huyện Văn Lâm', 'full_name_en' => 'Van Lam District', 'regions_code' => 33],
            ['name' => 'Yên Mỹ', 'full_name' => 'Huyện Yên Mỹ', 'full_name_en' => 'Yen My District', 'regions_code' => 33],

            // Các huyện của Thái Bình
            ['name' => 'Thái Bình', 'full_name' => 'Thành phố Thái Bình', 'full_name_en' => 'Thai Binh City', 'regions_code' => 34],
            ['name' => 'Đông Hưng', 'full_name' => 'Huyện Đông Hưng', 'full_name_en' => 'Dong Hung District', 'regions_code' => 34],
            ['name' => 'Hưng Hà', 'full_name' => 'Huyện Hưng Hà', 'full_name_en' => 'Hung Ha District', 'regions_code' => 34],
            ['name' => 'Kiến Xương', 'full_name' => 'Huyện Kiến Xương', 'full_name_en' => 'Kien Xuong District', 'regions_code' => 34],
            ['name' => 'Quỳnh Phụ', 'full_name' => 'Huyện Quỳnh Phụ', 'full_name_en' => 'Quynh Phu District', 'regions_code' => 34],
            ['name' => 'Thái Thụy', 'full_name' => 'Huyện Thái Thụy', 'full_name_en' => 'Thai Thuy District', 'regions_code' => 34],
            ['name' => 'Tiền Hải', 'full_name' => 'Huyện Tiền Hải', 'full_name_en' => 'Tien Hai District', 'regions_code' => 34],
            ['name' => 'Vũ Thư', 'full_name' => 'Huyện Vũ Thư', 'full_name_en' => 'Vu Thu District', 'regions_code' => 34],

            // Các huyện của Hà Nam
            ['name' => 'Phủ Lý', 'full_name' => 'Thành phố Phủ Lý', 'full_name_en' => 'Phu Ly City', 'regions_code' => 35],
            ['name' => 'Duy Tiên', 'full_name' => 'Thị xã Duy Tiên', 'full_name_en' => 'Duy Tien Town', 'regions_code' => 35],
            ['name' => 'Bình Lục', 'full_name' => 'Huyện Bình Lục', 'full_name_en' => 'Binh Luc District', 'regions_code' => 35],
            ['name' => 'Kim Bảng', 'full_name' => 'Huyện Kim Bảng', 'full_name_en' => 'Kim Bang District', 'regions_code' => 35],
            ['name' => 'Lý Nhân', 'full_name' => 'Huyện Lý Nhân', 'full_name_en' => 'Ly Nhan District', 'regions_code' => 35],
            ['name' => 'Thanh Liêm', 'full_name' => 'Huyện Thanh Liêm', 'full_name_en' => 'Thanh Liem District', 'regions_code' => 35],

            // Các huyện của Cà Mau
            ['name' => 'Cà Mau', 'full_name' => 'Thành phố Cà Mau', 'full_name_en' => 'Ca Mau City', 'regions_code' => 96],
            ['name' => 'Cái Nước', 'full_name' => 'Huyện Cái Nước', 'full_name_en' => 'Cai Nuoc District', 'regions_code' => 96],
            ['name' => 'Đầm Dơi', 'full_name' => 'Huyện Đầm Dơi', 'full_name_en' => 'Dam Doi District', 'regions_code' => 96],
            ['name' => 'Năm Căn', 'full_name' => 'Huyện Năm Căn', 'full_name_en' => 'Nam Can District', 'regions_code' => 96],
            ['name' => 'Ngọc Hiển', 'full_name' => 'Huyện Ngọc Hiển', 'full_name_en' => 'Ngoc Hien District', 'regions_code' => 96],
            ['name' => 'Phú Tân', 'full_name' => 'Huyện Phú Tân', 'full_name_en' => 'Phu Tan District', 'regions_code' => 96],
            ['name' => 'Thới Bình', 'full_name' => 'Huyện Thới Bình', 'full_name_en' => 'Thoi Binh District', 'regions_code' => 96],
            ['name' => 'Trần Văn Thời', 'full_name' => 'Huyện Trần Văn Thời', 'full_name_en' => 'Tran Van Thoi District', 'regions_code' => 96],
            ['name' => 'U Minh', 'full_name' => 'Huyện U Minh', 'full_name_en' => 'U Minh District', 'regions_code' => 96],

            // Các huyện của Hà Giang (regions_code = 2)
            ['name' => 'Hà Giang', 'full_name' => 'Thành phố Hà Giang', 'full_name_en' => 'Ha Giang City', 'regions_code' => 2],
            ['name' => 'Đồng Văn', 'full_name' => 'Huyện Đồng Văn', 'full_name_en' => 'Dong Van District', 'regions_code' => 2],
            ['name' => 'Mèo Vạc', 'full_name' => 'Huyện Mèo Vạc', 'full_name_en' => 'Meo Vac District', 'regions_code' => 2],
            ['name' => 'Yên Minh', 'full_name' => 'Huyện Yên Minh', 'full_name_en' => 'Yen Minh District', 'regions_code' => 2],
            ['name' => 'Quản Bạ', 'full_name' => 'Huyện Quản Bạ', 'full_name_en' => 'Quan Ba District', 'regions_code' => 2],
            ['name' => 'Vị Xuyên', 'full_name' => 'Huyện Vị Xuyên', 'full_name_en' => 'Vi Xuyen District', 'regions_code' => 2],
            ['name' => 'Bắc Mê', 'full_name' => 'Huyện Bắc Mê', 'full_name_en' => 'Bac Me District', 'regions_code' => 2],
            ['name' => 'Hoàng Su Phì', 'full_name' => 'Huyện Hoàng Su Phì', 'full_name_en' => 'Hoang Su Phi District', 'regions_code' => 2],
            ['name' => 'Xín Mần', 'full_name' => 'Huyện Xín Mần', 'full_name_en' => 'Xin Man District', 'regions_code' => 2],
            ['name' => 'Bắc Quang', 'full_name' => 'Huyện Bắc Quang', 'full_name_en' => 'Bac Quang District', 'regions_code' => 2],
            ['name' => 'Quang Bình', 'full_name' => 'Huyện Quang Bình', 'full_name_en' => 'Quang Binh District', 'regions_code' => 2],

            // Các huyện của Cao Bằng (regions_code = 4)
            ['name' => 'Cao Bằng', 'full_name' => 'Thành phố Cao Bằng', 'full_name_en' => 'Cao Bang City', 'regions_code' => 4],
            ['name' => 'Bảo Lạc', 'full_name' => 'Huyện Bảo Lạc', 'full_name_en' => 'Bao Lac District', 'regions_code' => 4],
            ['name' => 'Thông Nông', 'full_name' => 'Huyện Thông Nông', 'full_name_en' => 'Thong Nong District', 'regions_code' => 4],
            ['name' => 'Hà Quảng', 'full_name' => 'Huyện Hà Quảng', 'full_name_en' => 'Ha Quang District', 'regions_code' => 4],
            ['name' => 'Trà Lĩnh', 'full_name' => 'Huyện Trà Lĩnh', 'full_name_en' => 'Tra Linh District', 'regions_code' => 4],
            ['name' => 'Trùng Khánh', 'full_name' => 'Huyện Trùng Khánh', 'full_name_en' => 'Trung Khanh District', 'regions_code' => 4],
            ['name' => 'Hạ Lang', 'full_name' => 'Huyện Hạ Lang', 'full_name_en' => 'Ha Lang District', 'regions_code' => 4],
            ['name' => 'Quảng Uyên', 'full_name' => 'Huyện Quảng Uyên', 'full_name_en' => 'Quang Uyen District', 'regions_code' => 4],
            ['name' => 'Phục Hòa', 'full_name' => 'Huyện Phục Hòa', 'full_name_en' => 'Phuc Hoa District', 'regions_code' => 4],
            ['name' => 'Hòa An', 'full_name' => 'Huyện Hòa An', 'full_name_en' => 'Hoa An District', 'regions_code' => 4],
            ['name' => 'Nguyên Bình', 'full_name' => 'Huyện Nguyên Bình', 'full_name_en' => 'Nguyen Binh District', 'regions_code' => 4],
            ['name' => 'Thạch An', 'full_name' => 'Huyện Thạch An', 'full_name_en' => 'Thach An District', 'regions_code' => 4],

            // Các huyện của Bắc Kạn (regions_code = 6)
            ['name' => 'Bắc Kạn', 'full_name' => 'Thành phố Bắc Kạn', 'full_name_en' => 'Bac Kan City', 'regions_code' => 6],
            ['name' => 'Pác Nặm', 'full_name' => 'Huyện Pác Nặm', 'full_name_en' => 'Pac Nam District', 'regions_code' => 6],
            ['name' => 'Ba Bể', 'full_name' => 'Huyện Ba Bể', 'full_name_en' => 'Ba Be District', 'regions_code' => 6],
            ['name' => 'Ngân Sơn', 'full_name' => 'Huyện Ngân Sơn', 'full_name_en' => 'Ngan Son District', 'regions_code' => 6],
            ['name' => 'Bạch Thông', 'full_name' => 'Huyện Bạch Thông', 'full_name_en' => 'Bach Thong District', 'regions_code' => 6],
            ['name' => 'Chợ Đồn', 'full_name' => 'Huyện Chợ Đồn', 'full_name_en' => 'Cho Don District', 'regions_code' => 6],
            ['name' => 'Chợ Mới', 'full_name' => 'Huyện Chợ Mới', 'full_name_en' => 'Cho Moi District', 'regions_code' => 6],
            ['name' => 'Na Rì', 'full_name' => 'Huyện Na Rì', 'full_name_en' => 'Na Ri District', 'regions_code' => 6],

            // Các huyện của Tuyên Quang (regions_code = 8)
            ['name' => 'Tuyên Quang', 'full_name' => 'Thành phố Tuyên Quang', 'full_name_en' => 'Tuyen Quang City', 'regions_code' => 8],
            ['name' => 'Lâm Bình', 'full_name' => 'Huyện Lâm Bình', 'full_name_en' => 'Lam Binh District', 'regions_code' => 8],
            ['name' => 'Na Hang', 'full_name' => 'Huyện Na Hang', 'full_name_en' => 'Na Hang District', 'regions_code' => 8],
            ['name' => 'Chiêm Hóa', 'full_name' => 'Huyện Chiêm Hóa', 'full_name_en' => 'Chiem Hoa District', 'regions_code' => 8],
            ['name' => 'Hàm Yên', 'full_name' => 'Huyện Hàm Yên', 'full_name_en' => 'Ham Yen District', 'regions_code' => 8],
            ['name' => 'Yên Sơn', 'full_name' => 'Huyện Yên Sơn', 'full_name_en' => 'Yen Son District', 'regions_code' => 8],
            ['name' => 'Sơn Dương', 'full_name' => 'Huyện Sơn Dương', 'full_name_en' => 'Son Duong District', 'regions_code' => 8],

            // Các huyện của Thái Nguyên (regions_code = 19)
            ['name' => 'Thái Nguyên', 'full_name' => 'Thành phố Thái Nguyên', 'full_name_en' => 'Thai Nguyen City', 'regions_code' => 19],
            ['name' => 'Sông Công', 'full_name' => 'Thành phố Sông Công', 'full_name_en' => 'Song Cong City', 'regions_code' => 19],
            ['name' => 'Định Hóa', 'full_name' => 'Huyện Định Hóa', 'full_name_en' => 'Dinh Hoa District', 'regions_code' => 19],
            ['name' => 'Phú Lương', 'full_name' => 'Huyện Phú Lương', 'full_name_en' => 'Phu Luong District', 'regions_code' => 19],
            ['name' => 'Đồng Hỷ', 'full_name' => 'Huyện Đồng Hỷ', 'full_name_en' => 'Dong Hy District', 'regions_code' => 19],
            ['name' => 'Võ Nhai', 'full_name' => 'Huyện Võ Nhai', 'full_name_en' => 'Vo Nhai District', 'regions_code' => 19],
            ['name' => 'Đại Từ', 'full_name' => 'Huyện Đại Từ', 'full_name_en' => 'Dai Tu District', 'regions_code' => 19],
            ['name' => 'Phổ Yên', 'full_name' => 'Thị xã Phổ Yên', 'full_name_en' => 'Pho Yen Town', 'regions_code' => 19],
            ['name' => 'Phú Bình', 'full_name' => 'Huyện Phú Bình', 'full_name_en' => 'Phu Binh District', 'regions_code' => 19],

            // Các huyện của Lạng Sơn (regions_code = 20)
            ['name' => 'Lạng Sơn', 'full_name' => 'Thành phố Lạng Sơn', 'full_name_en' => 'Lang Son City', 'regions_code' => 20],
            ['name' => 'Tràng Định', 'full_name' => 'Huyện Tràng Định', 'full_name_en' => 'Trang Dinh District', 'regions_code' => 20],
            ['name' => 'Bình Gia', 'full_name' => 'Huyện Bình Gia', 'full_name_en' => 'Binh Gia District', 'regions_code' => 20],
            ['name' => 'Văn Lãng', 'full_name' => 'Huyện Văn Lãng', 'full_name_en' => 'Van Lang District', 'regions_code' => 20],
            ['name' => 'Cao Lộc', 'full_name' => 'Huyện Cao Lộc', 'full_name_en' => 'Cao Loc District', 'regions_code' => 20],
            ['name' => 'Văn Quan', 'full_name' => 'Huyện Văn Quan', 'full_name_en' => 'Van Quan District', 'regions_code' => 20],
            ['name' => 'Bắc Sơn', 'full_name' => 'Huyện Bắc Sơn', 'full_name_en' => 'Bac Son District', 'regions_code' => 20],
            ['name' => 'Hữu Lũng', 'full_name' => 'Huyện Hữu Lũng', 'full_name_en' => 'Huu Lung District', 'regions_code' => 20],
            ['name' => 'Chi Lăng', 'full_name' => 'Huyện Chi Lăng', 'full_name_en' => 'Chi Lang District', 'regions_code' => 20],
            ['name' => 'Lộc Bình', 'full_name' => 'Huyện Lộc Bình', 'full_name_en' => 'Loc Binh District', 'regions_code' => 20],
            ['name' => 'Đình Lập', 'full_name' => 'Huyện Đình Lập', 'full_name_en' => 'Dinh Lap District', 'regions_code' => 20],

            // Các huyện của Quảng Ninh (regions_code = 22)
            ['name' => 'Hạ Long', 'full_name' => 'Thành phố Hạ Long', 'full_name_en' => 'Ha Long City', 'regions_code' => 22],
            ['name' => 'Móng Cái', 'full_name' => 'Thành phố Móng Cái', 'full_name_en' => 'Mong Cai City', 'regions_code' => 22],
            ['name' => 'Cẩm Phả', 'full_name' => 'Thành phố Cẩm Phả', 'full_name_en' => 'Cam Pha City', 'regions_code' => 22],
            ['name' => 'Uông Bí', 'full_name' => 'Thành phố Uông Bí', 'full_name_en' => 'Uong Bi City', 'regions_code' => 22],
            ['name' => 'Bình Liêu', 'full_name' => 'Huyện Bình Liêu', 'full_name_en' => 'Binh Lieu District', 'regions_code' => 22],
            ['name' => 'Tiên Yên', 'full_name' => 'Huyện Tiên Yên', 'full_name_en' => 'Tien Yen District', 'regions_code' => 22],
            ['name' => 'Đầm Hà', 'full_name' => 'Huyện Đầm Hà', 'full_name_en' => 'Dam Ha District', 'regions_code' => 22],
            ['name' => 'Hải Hà', 'full_name' => 'Huyện Hải Hà', 'full_name_en' => 'Hai Ha District', 'regions_code' => 22],
            ['name' => 'Ba Chẽ', 'full_name' => 'Huyện Ba Chẽ', 'full_name_en' => 'Ba Che District', 'regions_code' => 22],
            ['name' => 'Vân Đồn', 'full_name' => 'Huyện Vân Đồn', 'full_name_en' => 'Van Don District', 'regions_code' => 22],
            ['name' => 'Hoành Bồ', 'full_name' => 'Huyện Hoành Bồ', 'full_name_en' => 'Hoanh Bo District', 'regions_code' => 22],
            ['name' => 'Đông Triều', 'full_name' => 'Thị xã Đông Triều', 'full_name_en' => 'Dong Trieu Town', 'regions_code' => 22],
            ['name' => 'Quảng Yên', 'full_name' => 'Thị xã Quảng Yên', 'full_name_en' => 'Quang Yen Town', 'regions_code' => 22],
            ['name' => 'Cô Tô', 'full_name' => 'Huyện Cô Tô', 'full_name_en' => 'Co To District', 'regions_code' => 22],

            // Các huyện của Bắc Giang (regions_code = 24)
            ['name' => 'Bắc Giang', 'full_name' => 'Thành phố Bắc Giang', 'full_name_en' => 'Bac Giang City', 'regions_code' => 24],
            ['name' => 'Yên Thế', 'full_name' => 'Huyện Yên Thế', 'full_name_en' => 'Yen The District', 'regions_code' => 24],
            ['name' => 'Tân Yên', 'full_name' => 'Huyện Tân Yên', 'full_name_en' => 'Tan Yen District', 'regions_code' => 24],
            ['name' => 'Lạng Giang', 'full_name' => 'Huyện Lạng Giang', 'full_name_en' => 'Lang Giang District', 'regions_code' => 24],
            ['name' => 'Lục Nam', 'full_name' => 'Huyện Lục Nam', 'full_name_en' => 'Luc Nam District', 'regions_code' => 24],
            ['name' => 'Lục Ngạn', 'full_name' => 'Huyện Lục Ngạn', 'full_name_en' => 'Luc Ngan District', 'regions_code' => 24],
            ['name' => 'Sơn Động', 'full_name' => 'Huyện Sơn Động', 'full_name_en' => 'Son Dong District', 'regions_code' => 24],
            ['name' => 'Yên Dũng', 'full_name' => 'Huyện Yên Dũng', 'full_name_en' => 'Yen Dung District', 'regions_code' => 24],
            ['name' => 'Việt Yên', 'full_name' => 'Huyện Việt Yên', 'full_name_en' => 'Viet Yen District', 'regions_code' => 24],
            ['name' => 'Hiệp Hòa', 'full_name' => 'Huyện Hiệp Hòa', 'full_name_en' => 'Hiep Hoa District', 'regions_code' => 24],

            // Các huyện của Phú Thọ (regions_code = 25)
            ['name' => 'Việt Trì', 'full_name' => 'Thành phố Việt Trì', 'full_name_en' => 'Viet Tri City', 'regions_code' => 25],
            ['name' => 'Phú Thọ', 'full_name' => 'Thị xã Phú Thọ', 'full_name_en' => 'Phu Tho Town', 'regions_code' => 25],
            ['name' => 'Đoan Hùng', 'full_name' => 'Huyện Đoan Hùng', 'full_name_en' => 'Doan Hung District', 'regions_code' => 25],
            ['name' => 'Hạ Hoà', 'full_name' => 'Huyện Hạ Hoà', 'full_name_en' => 'Ha Hoa District', 'regions_code' => 25],
            ['name' => 'Thanh Ba', 'full_name' => 'Huyện Thanh Ba', 'full_name_en' => 'Thanh Ba District', 'regions_code' => 25],
            ['name' => 'Phù Ninh', 'full_name' => 'Huyện Phù Ninh', 'full_name_en' => 'Phu Ninh District', 'regions_code' => 25],
            ['name' => 'Yên Lập', 'full_name' => 'Huyện Yên Lập', 'full_name_en' => 'Yen Lap District', 'regions_code' => 25],
            ['name' => 'Cẩm Khê', 'full_name' => 'Huyện Cẩm Khê', 'full_name_en' => 'Cam Khe District', 'regions_code' => 25],
            ['name' => 'Tam Nông', 'full_name' => 'Huyện Tam Nông', 'full_name_en' => 'Tam Nong District', 'regions_code' => 25],
            ['name' => 'Lâm Thao', 'full_name' => 'Huyện Lâm Thao', 'full_name_en' => 'Lam Thao District', 'regions_code' => 25],
            ['name' => 'Thanh Sơn', 'full_name' => 'Huyện Thanh Sơn', 'full_name_en' => 'Thanh Son District', 'regions_code' => 25],
            ['name' => 'Thanh Thuỷ', 'full_name' => 'Huyện Thanh Thuỷ', 'full_name_en' => 'Thanh Thuy District', 'regions_code' => 25],
            ['name' => 'Tân Sơn', 'full_name' => 'Huyện Tân Sơn', 'full_name_en' => 'Tan Son District', 'regions_code' => 25],

            // Các huyện của Lào Cai (regions_code = 10)
            ['name' => 'Lào Cai', 'full_name' => 'Thành phố Lào Cai', 'full_name_en' => 'Lao Cai City', 'regions_code' => 10],
            ['name' => 'Bát Xát', 'full_name' => 'Huyện Bát Xát', 'full_name_en' => 'Bat Xat District', 'regions_code' => 10],
            ['name' => 'Mường Khương', 'full_name' => 'Huyện Mường Khương', 'full_name_en' => 'Muong Khuong District', 'regions_code' => 10],
            ['name' => 'Si Ma Cai', 'full_name' => 'Huyện Si Ma Cai', 'full_name_en' => 'Si Ma Cai District', 'regions_code' => 10],
            ['name' => 'Bắc Hà', 'full_name' => 'Huyện Bắc Hà', 'full_name_en' => 'Bac Ha District', 'regions_code' => 10],
            ['name' => 'Bảo Thắng', 'full_name' => 'Huyện Bảo Thắng', 'full_name_en' => 'Bao Thang District', 'regions_code' => 10],
            ['name' => 'Bảo Yên', 'full_name' => 'Huyện Bảo Yên', 'full_name_en' => 'Bao Yen District', 'regions_code' => 10],
            ['name' => 'Sa Pa', 'full_name' => 'Huyện Sa Pa', 'full_name_en' => 'Sa Pa District', 'regions_code' => 10],
            ['name' => 'Văn Bàn', 'full_name' => 'Huyện Văn Bàn', 'full_name_en' => 'Van Ban District', 'regions_code' => 10],

            // Các huyện của Điện Biên (regions_code = 11)
            ['name' => 'Điện Biên Phủ', 'full_name' => 'Thành phố Điện Biên Phủ', 'full_name_en' => 'Dien Bien Phu City', 'regions_code' => 11],
            ['name' => 'Mường Lay', 'full_name' => 'Thị xã Mường Lay', 'full_name_en' => 'Muong Lay Town', 'regions_code' => 11],
            ['name' => 'Mường Nhé', 'full_name' => 'Huyện Mường Nhé', 'full_name_en' => 'Muong Nhe District', 'regions_code' => 11],
            ['name' => 'Mường Chà', 'full_name' => 'Huyện Mường Chà', 'full_name_en' => 'Muong Cha District', 'regions_code' => 11],
            ['name' => 'Tủa Chùa', 'full_name' => 'Huyện Tủa Chùa', 'full_name_en' => 'Tua Chua District', 'regions_code' => 11],
            ['name' => 'Tuần Giáo', 'full_name' => 'Huyện Tuần Giáo', 'full_name_en' => 'Tuan Giao District', 'regions_code' => 11],
            ['name' => 'Điện Biên', 'full_name' => 'Huyện Điện Biên', 'full_name_en' => 'Dien Bien District', 'regions_code' => 11],
            ['name' => 'Điện Biên Đông', 'full_name' => 'Huyện Điện Biên Đông', 'full_name_en' => 'Dien Bien Dong District', 'regions_code' => 11],
            ['name' => 'Mường Ảng', 'full_name' => 'Huyện Mường Ảng', 'full_name_en' => 'Muong Ang District', 'regions_code' => 11],
            ['name' => 'Nậm Pồ', 'full_name' => 'Huyện Nậm Pồ', 'full_name_en' => 'Nam Po District', 'regions_code' => 11],

            // Các huyện của Lai Châu (regions_code = 12)
            ['name' => 'Lai Châu', 'full_name' => 'Thành phố Lai Châu', 'full_name_en' => 'Lai Chau City', 'regions_code' => 12],
            ['name' => 'Tam Đường', 'full_name' => 'Huyện Tam Đường', 'full_name_en' => 'Tam Duong District', 'regions_code' => 12],
            ['name' => 'Mường Tè', 'full_name' => 'Huyện Mường Tè', 'full_name_en' => 'Muong Te District', 'regions_code' => 12],
            ['name' => 'Sìn Hồ', 'full_name' => 'Huyện Sìn Hồ', 'full_name_en' => 'Sin Ho District', 'regions_code' => 12],
            ['name' => 'Phong Thổ', 'full_name' => 'Huyện Phong Thổ', 'full_name_en' => 'Phong Tho District', 'regions_code' => 12],
            ['name' => 'Than Uyên', 'full_name' => 'Huyện Than Uyên', 'full_name_en' => 'Than Uyen District', 'regions_code' => 12],
            ['name' => 'Tân Uyên', 'full_name' => 'Huyện Tân Uyên', 'full_name_en' => 'Tan Uyen District', 'regions_code' => 12],
            ['name' => 'Nậm Nhùn', 'full_name' => 'Huyện Nậm Nhùn', 'full_name_en' => 'Nam Nhun District', 'regions_code' => 12],

            // Các huyện của Sơn La (regions_code = 14)
            ['name' => 'Sơn La', 'full_name' => 'Thành phố Sơn La', 'full_name_en' => 'Son La City', 'regions_code' => 14],
            ['name' => 'Quỳnh Nhai', 'full_name' => 'Huyện Quỳnh Nhai', 'full_name_en' => 'Quynh Nhai District', 'regions_code' => 14],
            ['name' => 'Thuận Châu', 'full_name' => 'Huyện Thuận Châu', 'full_name_en' => 'Thuan Chau District', 'regions_code' => 14],
            ['name' => 'Mường La', 'full_name' => 'Huyện Mường La', 'full_name_en' => 'Muong La District', 'regions_code' => 14],
            ['name' => 'Bắc Yên', 'full_name' => 'Huyện Bắc Yên', 'full_name_en' => 'Bac Yen District', 'regions_code' => 14],
            ['name' => 'Phù Yên', 'full_name' => 'Huyện Phù Yên', 'full_name_en' => 'Phu Yen District', 'regions_code' => 14],
            ['name' => 'Mộc Châu', 'full_name' => 'Huyện Mộc Châu', 'full_name_en' => 'Moc Chau District', 'regions_code' => 14],
            ['name' => 'Yên Châu', 'full_name' => 'Huyện Yên Châu', 'full_name_en' => 'Yen Chau District', 'regions_code' => 14],
            ['name' => 'Mai Sơn', 'full_name' => 'Huyện Mai Sơn', 'full_name_en' => 'Mai Son District', 'regions_code' => 14],
            ['name' => 'Sông Mã', 'full_name' => 'Huyện Sông Mã', 'full_name_en' => 'Song Ma District', 'regions_code' => 14],
            ['name' => 'Sốp Cộp', 'full_name' => 'Huyện Sốp Cộp', 'full_name_en' => 'Sop Cop District', 'regions_code' => 14],
            ['name' => 'Vân Hồ', 'full_name' => 'Huyện Vân Hồ', 'full_name_en' => 'Van Ho District', 'regions_code' => 14],

            // Các huyện của Yên Bái (regions_code = 15)
            ['name' => 'Yên Bái', 'full_name' => 'Thành phố Yên Bái', 'full_name_en' => 'Yen Bai City', 'regions_code' => 15],
            ['name' => 'Nghĩa Lộ', 'full_name' => 'Thị xã Nghĩa Lộ', 'full_name_en' => 'Nghia Lo Town', 'regions_code' => 15],
            ['name' => 'Lục Yên', 'full_name' => 'Huyện Lục Yên', 'full_name_en' => 'Luc Yen District', 'regions_code' => 15],
            ['name' => 'Văn Yên', 'full_name' => 'Huyện Văn Yên', 'full_name_en' => 'Van Yen District', 'regions_code' => 15],
            ['name' => 'Mù Căng Chải', 'full_name' => 'Huyện Mù Căng Chải', 'full_name_en' => 'Mu Cang Chai District', 'regions_code' => 15],
            ['name' => 'Trấn Yên', 'full_name' => 'Huyện Trấn Yên', 'full_name_en' => 'Tran Yen District', 'regions_code' => 15],
            ['name' => 'Trạm Tấu', 'full_name' => 'Huyện Trạm Tấu', 'full_name_en' => 'Tram Tau District', 'regions_code' => 15],
            ['name' => 'Văn Chấn', 'full_name' => 'Huyện Văn Chấn', 'full_name_en' => 'Van Chan District', 'regions_code' => 15],
            ['name' => 'Yên Bình', 'full_name' => 'Huyện Yên Bình', 'full_name_en' => 'Yen Binh District', 'regions_code' => 15],

            // Các huyện của Hoà Bình (regions_code = 17)
            ['name' => 'Hoà Bình', 'full_name' => 'Thành phố Hoà Bình', 'full_name_en' => 'Hoa Binh City', 'regions_code' => 17],
            ['name' => 'Đà Bắc', 'full_name' => 'Huyện Đà Bắc', 'full_name_en' => 'Da Bac District', 'regions_code' => 17],
            ['name' => 'Kỳ Sơn', 'full_name' => 'Huyện Kỳ Sơn', 'full_name_en' => 'Ky Son District', 'regions_code' => 17],
            ['name' => 'Lương Sơn', 'full_name' => 'Huyện Lương Sơn', 'full_name_en' => 'Luong Son District', 'regions_code' => 17],
            ['name' => 'Kim Bôi', 'full_name' => 'Huyện Kim Bôi', 'full_name_en' => 'Kim Boi District', 'regions_code' => 17],
            ['name' => 'Cao Phong', 'full_name' => 'Huyện Cao Phong', 'full_name_en' => 'Cao Phong District', 'regions_code' => 17],
            ['name' => 'Tân Lạc', 'full_name' => 'Huyện Tân Lạc', 'full_name_en' => 'Tan Lac District', 'regions_code' => 17],
            ['name' => 'Mai Châu', 'full_name' => 'Huyện Mai Châu', 'full_name_en' => 'Mai Chau District', 'regions_code' => 17],
            ['name' => 'Lạc Sơn', 'full_name' => 'Huyện Lạc Sơn', 'full_name_en' => 'Lac Son District', 'regions_code' => 17],
            ['name' => 'Yên Thuỷ', 'full_name' => 'Huyện Yên Thuỷ', 'full_name_en' => 'Yen Thuy District', 'regions_code' => 17],
            ['name' => 'Lạc Thuỷ', 'full_name' => 'Huyện Lạc Thuỷ', 'full_name_en' => 'Lac Thuy District', 'regions_code' => 17],

            // Các huyện của Bình Phước (regions_code = 70)
            ['name' => 'Đồng Xoài', 'full_name' => 'Thành phố Đồng Xoài', 'full_name_en' => 'Dong Xoai City', 'regions_code' => 70],
            ['name' => 'Bình Long', 'full_name' => 'Thị xã Bình Long', 'full_name_en' => 'Binh Long Town', 'regions_code' => 70],
            ['name' => 'Phước Long', 'full_name' => 'Thị xã Phước Long', 'full_name_en' => 'Phuoc Long Town', 'regions_code' => 70],
            ['name' => 'Bù Gia Mập', 'full_name' => 'Huyện Bù Gia Mập', 'full_name_en' => 'Bu Gia Map District', 'regions_code' => 70],
            ['name' => 'Lộc Ninh', 'full_name' => 'Huyện Lộc Ninh', 'full_name_en' => 'Loc Ninh District', 'regions_code' => 70],
            ['name' => 'Bù Đốp', 'full_name' => 'Huyện Bù Đốp', 'full_name_en' => 'Bu Dop District', 'regions_code' => 70],
            ['name' => 'Hớn Quản', 'full_name' => 'Huyện Hớn Quản', 'full_name_en' => 'Hon Quan District', 'regions_code' => 70],
            ['name' => 'Đồng Phú', 'full_name' => 'Huyện Đồng Phú', 'full_name_en' => 'Dong Phu District', 'regions_code' => 70],
            ['name' => 'Bù Đăng', 'full_name' => 'Huyện Bù Đăng', 'full_name_en' => 'Bu Dang District', 'regions_code' => 70],
            ['name' => 'Chơn Thành', 'full_name' => 'Huyện Chơn Thành', 'full_name_en' => 'Chon Thanh District', 'regions_code' => 70],
            ['name' => 'Phú Riềng', 'full_name' => 'Huyện Phú Riềng', 'full_name_en' => 'Phu Rieng District', 'regions_code' => 70],

            // Các huyện của Tây Ninh (regions_code = 72)
            ['name' => 'Tây Ninh', 'full_name' => 'Thành phố Tây Ninh', 'full_name_en' => 'Tay Ninh City', 'regions_code' => 72],
            ['name' => 'Tân Biên', 'full_name' => 'Huyện Tân Biên', 'full_name_en' => 'Tan Bien District', 'regions_code' => 72],
            ['name' => 'Tân Châu', 'full_name' => 'Huyện Tân Châu', 'full_name_en' => 'Tan Chau District', 'regions_code' => 72],
            ['name' => 'Dương Minh Châu', 'full_name' => 'Huyện Dương Minh Châu', 'full_name_en' => 'Duong Minh Chau District', 'regions_code' => 72],
            ['name' => 'Châu Thành', 'full_name' => 'Huyện Châu Thành', 'full_name_en' => 'Chau Thanh District', 'regions_code' => 72],
            ['name' => 'Hòa Thành', 'full_name' => 'Thị xã Hòa Thành', 'full_name_en' => 'Hoa Thanh Town', 'regions_code' => 72],
            ['name' => 'Gò Dầu', 'full_name' => 'Huyện Gò Dầu', 'full_name_en' => 'Go Dau District', 'regions_code' => 72],
            ['name' => 'Bến Cầu', 'full_name' => 'Huyện Bến Cầu', 'full_name_en' => 'Ben Cau District', 'regions_code' => 72],
            ['name' => 'Trảng Bàng', 'full_name' => 'Thị xã Trảng Bàng', 'full_name_en' => 'Trang Bang Town', 'regions_code' => 72],

            // Các huyện của Bình Dương (regions_code = 74)
            ['name' => 'Thủ Dầu Một', 'full_name' => 'Thành phố Thủ Dầu Một', 'full_name_en' => 'Thu Dau Mot City', 'regions_code' => 74],
            ['name' => 'Bàu Bàng', 'full_name' => 'Huyện Bàu Bàng', 'full_name_en' => 'Bau Bang District', 'regions_code' => 74],
            ['name' => 'Dầu Tiếng', 'full_name' => 'Huyện Dầu Tiếng', 'full_name_en' => 'Dau Tieng District', 'regions_code' => 74],
            ['name' => 'Bến Cát', 'full_name' => 'Thị xã Bến Cát', 'full_name_en' => 'Ben Cat Town', 'regions_code' => 74],
            ['name' => 'Phú Giáo', 'full_name' => 'Huyện Phú Giáo', 'full_name_en' => 'Phu Giao District', 'regions_code' => 74],
            ['name' => 'Tân Uyên', 'full_name' => 'Thị xã Tân Uyên', 'full_name_en' => 'Tan Uyen Town', 'regions_code' => 74],
            ['name' => 'Dĩ An', 'full_name' => 'Thành phố Dĩ An', 'full_name_en' => 'Di An City', 'regions_code' => 74],
            ['name' => 'Thuận An', 'full_name' => 'Thành phố Thuận An', 'full_name_en' => 'Thuan An City', 'regions_code' => 74],
            ['name' => 'Bắc Tân Uyên', 'full_name' => 'Huyện Bắc Tân Uyên', 'full_name_en' => 'Bac Tan Uyen District', 'regions_code' => 74],

            // Các huyện của Đồng Nai (regions_code = 75)
            ['name' => 'Biên Hòa', 'full_name' => 'Thành phố Biên Hòa', 'full_name_en' => 'Bien Hoa City', 'regions_code' => 75],
            ['name' => 'Long Khánh', 'full_name' => 'Thành phố Long Khánh', 'full_name_en' => 'Long Khanh City', 'regions_code' => 75],
            ['name' => 'Tân Phú', 'full_name' => 'Huyện Tân Phú', 'full_name_en' => 'Tan Phu District', 'regions_code' => 75],
            ['name' => 'Vĩnh Cửu', 'full_name' => 'Huyện Vĩnh Cửu', 'full_name_en' => 'Vinh Cuu District', 'regions_code' => 75],
            ['name' => 'Định Quán', 'full_name' => 'Huyện Định Quán', 'full_name_en' => 'Dinh Quan District', 'regions_code' => 75],
            ['name' => 'Trảng Bom', 'full_name' => 'Huyện Trảng Bom', 'full_name_en' => 'Trang Bom District', 'regions_code' => 75],
            ['name' => 'Thống Nhất', 'full_name' => 'Huyện Thống Nhất', 'full_name_en' => 'Thong Nhat District', 'regions_code' => 75],
            ['name' => 'Cẩm Mỹ', 'full_name' => 'Huyện Cẩm Mỹ', 'full_name_en' => 'Cam My District', 'regions_code' => 75],
            ['name' => 'Long Thành', 'full_name' => 'Huyện Long Thành', 'full_name_en' => 'Long Thanh District', 'regions_code' => 75],
            ['name' => 'Xuân Lộc', 'full_name' => 'Huyện Xuân Lộc', 'full_name_en' => 'Xuan Loc District', 'regions_code' => 75],
            ['name' => 'Nhơn Trạch', 'full_name' => 'Huyện Nhơn Trạch', 'full_name_en' => 'Nhon Trach District', 'regions_code' => 75],

            // Các huyện của Bà Rịa - Vũng Tàu (regions_code = 77)
            ['name' => 'Vũng Tàu', 'full_name' => 'Thành phố Vũng Tàu', 'full_name_en' => 'Vung Tau City', 'regions_code' => 77],
            ['name' => 'Bà Rịa', 'full_name' => 'Thành phố Bà Rịa', 'full_name_en' => 'Ba Ria City', 'regions_code' => 77],
            ['name' => 'Châu Đức', 'full_name' => 'Huyện Châu Đức', 'full_name_en' => 'Chau Duc District', 'regions_code' => 77],
            ['name' => 'Xuyên Mộc', 'full_name' => 'Huyện Xuyên Mộc', 'full_name_en' => 'Xuyen Moc District', 'regions_code' => 77],
            ['name' => 'Long Điền', 'full_name' => 'Huyện Long Điền', 'full_name_en' => 'Long Dien District', 'regions_code' => 77],
            ['name' => 'Đất Đỏ', 'full_name' => 'Huyện Đất Đỏ', 'full_name_en' => 'Dat Do District', 'regions_code' => 77],
            ['name' => 'Tân Thành', 'full_name' => 'Thị xã Phú Mỹ', 'full_name_en' => 'Phu My Town', 'regions_code' => 77],
            ['name' => 'Côn Đảo', 'full_name' => 'Huyện Côn Đảo', 'full_name_en' => 'Con Dao District', 'regions_code' => 77],

            // Các huyện của Nam Định (regions_code = 36)
            ['name' => 'Nam Định', 'full_name' => 'Thành phố Nam Định', 'full_name_en' => 'Nam Dinh City', 'regions_code' => 36],
            ['name' => 'Mỹ Lộc', 'full_name' => 'Huyện Mỹ Lộc', 'full_name_en' => 'My Loc District', 'regions_code' => 36],
            ['name' => 'Vụ Bản', 'full_name' => 'Huyện Vụ Bản', 'full_name_en' => 'Vu Ban District', 'regions_code' => 36],
            ['name' => 'Ý Yên', 'full_name' => 'Huyện Ý Yên', 'full_name_en' => 'Y Yen District', 'regions_code' => 36],
            ['name' => 'Nghĩa Hưng', 'full_name' => 'Huyện Nghĩa Hưng', 'full_name_en' => 'Nghia Hung District', 'regions_code' => 36],
            ['name' => 'Nam Trực', 'full_name' => 'Huyện Nam Trực', 'full_name_en' => 'Nam Truc District', 'regions_code' => 36],
            ['name' => 'Trực Ninh', 'full_name' => 'Huyện Trực Ninh', 'full_name_en' => 'Truc Ninh District', 'regions_code' => 36],
            ['name' => 'Xuân Trường', 'full_name' => 'Huyện Xuân Trường', 'full_name_en' => 'Xuan Truong District', 'regions_code' => 36],
            ['name' => 'Giao Thủy', 'full_name' => 'Huyện Giao Thủy', 'full_name_en' => 'Giao Thuy District', 'regions_code' => 36],
            ['name' => 'Hải Hậu', 'full_name' => 'Huyện Hải Hậu', 'full_name_en' => 'Hai Hau District', 'regions_code' => 36],

            // Các huyện của Ninh Bình (regions_code = 37)
            ['name' => 'Ninh Bình', 'full_name' => 'Thành phố Ninh Bình', 'full_name_en' => 'Ninh Binh City', 'regions_code' => 37],
            ['name' => 'Tam Điệp', 'full_name' => 'Thành phố Tam Điệp', 'full_name_en' => 'Tam Diep City', 'regions_code' => 37],
            ['name' => 'Nho Quan', 'full_name' => 'Huyện Nho Quan', 'full_name_en' => 'Nho Quan District', 'regions_code' => 37],
            ['name' => 'Gia Viễn', 'full_name' => 'Huyện Gia Viễn', 'full_name_en' => 'Gia Vien District', 'regions_code' => 37],
            ['name' => 'Hoa Lư', 'full_name' => 'Huyện Hoa Lư', 'full_name_en' => 'Hoa Lu District', 'regions_code' => 37],
            ['name' => 'Yên Khánh', 'full_name' => 'Huyện Yên Khánh', 'full_name_en' => 'Yen Khanh District', 'regions_code' => 37],
            ['name' => 'Kim Sơn', 'full_name' => 'Huyện Kim Sơn', 'full_name_en' => 'Kim Son District', 'regions_code' => 37],
            ['name' => 'Yên Mô', 'full_name' => 'Huyện Yên Mô', 'full_name_en' => 'Yen Mo District', 'regions_code' => 37],

            // Các huyện của Thanh Hóa (regions_code = 38)
            ['name' => 'Thanh Hóa', 'full_name' => 'Thành phố Thanh Hóa', 'full_name_en' => 'Thanh Hoa City', 'regions_code' => 38],
            ['name' => 'Bỉm Sơn', 'full_name' => 'Thị xã Bỉm Sơn', 'full_name_en' => 'Bim Son Town', 'regions_code' => 38],
            ['name' => 'Sầm Sơn', 'full_name' => 'Thành phố Sầm Sơn', 'full_name_en' => 'Sam Son City', 'regions_code' => 38],
            ['name' => 'Mường Lát', 'full_name' => 'Huyện Mường Lát', 'full_name_en' => 'Muong Lat District', 'regions_code' => 38],
            ['name' => 'Quan Hóa', 'full_name' => 'Huyện Quan Hóa', 'full_name_en' => 'Quan Hoa District', 'regions_code' => 38],
            ['name' => 'Bá Thước', 'full_name' => 'Huyện Bá Thước', 'full_name_en' => 'Ba Thuoc District', 'regions_code' => 38],
            ['name' => 'Quan Sơn', 'full_name' => 'Huyện Quan Sơn', 'full_name_en' => 'Quan Son District', 'regions_code' => 38],
            ['name' => 'Lang Chánh', 'full_name' => 'Huyện Lang Chánh', 'full_name_en' => 'Lang Chanh District', 'regions_code' => 38],
            ['name' => 'Ngọc Lặc', 'full_name' => 'Huyện Ngọc Lặc', 'full_name_en' => 'Ngoc Lac District', 'regions_code' => 38],
            ['name' => 'Cẩm Thủy', 'full_name' => 'Huyện Cẩm Thủy', 'full_name_en' => 'Cam Thuy District', 'regions_code' => 38],
            ['name' => 'Thạch Thành', 'full_name' => 'Huyện Thạch Thành', 'full_name_en' => 'Thach Thanh District', 'regions_code' => 38],
            ['name' => 'Hà Trung', 'full_name' => 'Huyện Hà Trung', 'full_name_en' => 'Ha Trung District', 'regions_code' => 38],
            ['name' => 'Vĩnh Lộc', 'full_name' => 'Huyện Vĩnh Lộc', 'full_name_en' => 'Vinh Loc District', 'regions_code' => 38],
            ['name' => 'Yên Định', 'full_name' => 'Huyện Yên Định', 'full_name_en' => 'Yen Dinh District', 'regions_code' => 38],
            ['name' => 'Thọ Xuân', 'full_name' => 'Huyện Thọ Xuân', 'full_name_en' => 'Tho Xuan District', 'regions_code' => 38],
            ['name' => 'Thường Xuân', 'full_name' => 'Huyện Thường Xuân', 'full_name_en' => 'Thuong Xuan District', 'regions_code' => 38],
            ['name' => 'Triệu Sơn', 'full_name' => 'Huyện Triệu Sơn', 'full_name_en' => 'Trieu Son District', 'regions_code' => 38],
            ['name' => 'Thiệu Hóa', 'full_name' => 'Huyện Thiệu Hóa', 'full_name_en' => 'Thieu Hoa District', 'regions_code' => 38],
            ['name' => 'Hoằng Hóa', 'full_name' => 'Huyện Hoằng Hóa', 'full_name_en' => 'Hoang Hoa District', 'regions_code' => 38],
            ['name' => 'Hậu Lộc', 'full_name' => 'Huyện Hậu Lộc', 'full_name_en' => 'Hau Loc District', 'regions_code' => 38],
            ['name' => 'Nga Sơn', 'full_name' => 'Huyện Nga Sơn', 'full_name_en' => 'Nga Son District', 'regions_code' => 38],
            ['name' => 'Như Xuân', 'full_name' => 'Huyện Như Xuân', 'full_name_en' => 'Nhu Xuan District', 'regions_code' => 38],
            ['name' => 'Như Thanh', 'full_name' => 'Huyện Như Thanh', 'full_name_en' => 'Nhu Thanh District', 'regions_code' => 38],
            ['name' => 'Nông Cống', 'full_name' => 'Huyện Nông Cống', 'full_name_en' => 'Nong Cong District', 'regions_code' => 38],
            ['name' => 'Đông Sơn', 'full_name' => 'Huyện Đông Sơn', 'full_name_en' => 'Dong Son District', 'regions_code' => 38],
            ['name' => 'Quảng Xương', 'full_name' => 'Huyện Quảng Xương', 'full_name_en' => 'Quang Xuong District', 'regions_code' => 38],
            ['name' => 'Tĩnh Gia', 'full_name' => 'Thị xã Nghi Sơn', 'full_name_en' => 'Nghi Son Town', 'regions_code' => 38],
            // Các huyện của Hà Giang (regions_code = 2)
            ['name' => 'Hà Giang', 'full_name' => 'Thành phố Hà Giang', 'full_name_en' => 'Ha Giang City', 'regions_code' => 2],
            ['name' => 'Đồng Văn', 'full_name' => 'Huyện Đồng Văn', 'full_name_en' => 'Dong Van District', 'regions_code' => 2],
            ['name' => 'Mèo Vạc', 'full_name' => 'Huyện Mèo Vạc', 'full_name_en' => 'Meo Vac District', 'regions_code' => 2],
            ['name' => 'Yên Minh', 'full_name' => 'Huyện Yên Minh', 'full_name_en' => 'Yen Minh District', 'regions_code' => 2],
            ['name' => 'Quản Bạ', 'full_name' => 'Huyện Quản Bạ', 'full_name_en' => 'Quan Ba District', 'regions_code' => 2],
            ['name' => 'Vị Xuyên', 'full_name' => 'Huyện Vị Xuyên', 'full_name_en' => 'Vi Xuyen District', 'regions_code' => 2],
            ['name' => 'Bắc Mê', 'full_name' => 'Huyện Bắc Mê', 'full_name_en' => 'Bac Me District', 'regions_code' => 2],
            ['name' => 'Hoàng Su Phì', 'full_name' => 'Huyện Hoàng Su Phì', 'full_name_en' => 'Hoang Su Phi District', 'regions_code' => 2],
            ['name' => 'Xín Mần', 'full_name' => 'Huyện Xín Mần', 'full_name_en' => 'Xin Man District', 'regions_code' => 2],
            ['name' => 'Bắc Quang', 'full_name' => 'Huyện Bắc Quang', 'full_name_en' => 'Bac Quang District', 'regions_code' => 2],
            ['name' => 'Quang Bình', 'full_name' => 'Huyện Quang Bình', 'full_name_en' => 'Quang Binh District', 'regions_code' => 2],

            // Các huyện của Cao Bằng (regions_code = 4)
            ['name' => 'Cao Bằng', 'full_name' => 'Thành phố Cao Bằng', 'full_name_en' => 'Cao Bang City', 'regions_code' => 4],
            ['name' => 'Bảo Lạc', 'full_name' => 'Huyện Bảo Lạc', 'full_name_en' => 'Bao Lac District', 'regions_code' => 4],
            ['name' => 'Thông Nông', 'full_name' => 'Huyện Thông Nông', 'full_name_en' => 'Thong Nong District', 'regions_code' => 4],
            ['name' => 'Hà Quảng', 'full_name' => 'Huyện Hà Quảng', 'full_name_en' => 'Ha Quang District', 'regions_code' => 4],
            ['name' => 'Trà Lĩnh', 'full_name' => 'Huyện Trà Lĩnh', 'full_name_en' => 'Tra Linh District', 'regions_code' => 4],
            ['name' => 'Trùng Khánh', 'full_name' => 'Huyện Trùng Khánh', 'full_name_en' => 'Trung Khanh District', 'regions_code' => 4],
            ['name' => 'Hạ Lang', 'full_name' => 'Huyện Hạ Lang', 'full_name_en' => 'Ha Lang District', 'regions_code' => 4],
            ['name' => 'Quảng Uyên', 'full_name' => 'Huyện Quảng Uyên', 'full_name_en' => 'Quang Uyen District', 'regions_code' => 4],
            ['name' => 'Phục Hòa', 'full_name' => 'Huyện Phục Hòa', 'full_name_en' => 'Phuc Hoa District', 'regions_code' => 4],
            ['name' => 'Hòa An', 'full_name' => 'Huyện Hòa An', 'full_name_en' => 'Hoa An District', 'regions_code' => 4],
            ['name' => 'Nguyên Bình', 'full_name' => 'Huyện Nguyên Bình', 'full_name_en' => 'Nguyen Binh District', 'regions_code' => 4],
            ['name' => 'Thạch An', 'full_name' => 'Huyện Thạch An', 'full_name_en' => 'Thach An District', 'regions_code' => 4],

            // Các huyện của Bắc Kạn (regions_code = 6)
            ['name' => 'Bắc Kạn', 'full_name' => 'Thành phố Bắc Kạn', 'full_name_en' => 'Bac Kan City', 'regions_code' => 6],
            ['name' => 'Pác Nặm', 'full_name' => 'Huyện Pác Nặm', 'full_name_en' => 'Pac Nam District', 'regions_code' => 6],
            ['name' => 'Ba Bể', 'full_name' => 'Huyện Ba Bể', 'full_name_en' => 'Ba Be District', 'regions_code' => 6],
            ['name' => 'Ngân Sơn', 'full_name' => 'Huyện Ngân Sơn', 'full_name_en' => 'Ngan Son District', 'regions_code' => 6],
            ['name' => 'Bạch Thông', 'full_name' => 'Huyện Bạch Thông', 'full_name_en' => 'Bach Thong District', 'regions_code' => 6],
            ['name' => 'Chợ Đồn', 'full_name' => 'Huyện Chợ Đồn', 'full_name_en' => 'Cho Don District', 'regions_code' => 6],
            ['name' => 'Chợ Mới', 'full_name' => 'Huyện Chợ Mới', 'full_name_en' => 'Cho Moi District', 'regions_code' => 6],
            ['name' => 'Na Rì', 'full_name' => 'Huyện Na Rì', 'full_name_en' => 'Na Ri District', 'regions_code' => 6],

            // Các huyện của Tuyên Quang (regions_code = 8)
            ['name' => 'Tuyên Quang', 'full_name' => 'Thành phố Tuyên Quang', 'full_name_en' => 'Tuyen Quang City', 'regions_code' => 8],
            ['name' => 'Lâm Bình', 'full_name' => 'Huyện Lâm Bình', 'full_name_en' => 'Lam Binh District', 'regions_code' => 8],
            ['name' => 'Na Hang', 'full_name' => 'Huyện Na Hang', 'full_name_en' => 'Na Hang District', 'regions_code' => 8],
            ['name' => 'Chiêm Hóa', 'full_name' => 'Huyện Chiêm Hóa', 'full_name_en' => 'Chiem Hoa District', 'regions_code' => 8],
            ['name' => 'Hàm Yên', 'full_name' => 'Huyện Hàm Yên', 'full_name_en' => 'Ham Yen District', 'regions_code' => 8],
            ['name' => 'Yên Sơn', 'full_name' => 'Huyện Yên Sơn', 'full_name_en' => 'Yen Son District', 'regions_code' => 8],
            ['name' => 'Sơn Dương', 'full_name' => 'Huyện Sơn Dương', 'full_name_en' => 'Son Duong District', 'regions_code' => 8],

            // Các huyện của Thái Nguyên (regions_code = 19)
            ['name' => 'Thái Nguyên', 'full_name' => 'Thành phố Thái Nguyên', 'full_name_en' => 'Thai Nguyen City', 'regions_code' => 19],
            ['name' => 'Sông Công', 'full_name' => 'Thành phố Sông Công', 'full_name_en' => 'Song Cong City', 'regions_code' => 19],
            ['name' => 'Định Hóa', 'full_name' => 'Huyện Định Hóa', 'full_name_en' => 'Dinh Hoa District', 'regions_code' => 19],
            ['name' => 'Phú Lương', 'full_name' => 'Huyện Phú Lương', 'full_name_en' => 'Phu Luong District', 'regions_code' => 19],
            ['name' => 'Đồng Hỷ', 'full_name' => 'Huyện Đồng Hỷ', 'full_name_en' => 'Dong Hy District', 'regions_code' => 19],
            ['name' => 'Võ Nhai', 'full_name' => 'Huyện Võ Nhai', 'full_name_en' => 'Vo Nhai District', 'regions_code' => 19],
            ['name' => 'Đại Từ', 'full_name' => 'Huyện Đại Từ', 'full_name_en' => 'Dai Tu District', 'regions_code' => 19],
            ['name' => 'Phổ Yên', 'full_name' => 'Thị xã Phổ Yên', 'full_name_en' => 'Pho Yen Town', 'regions_code' => 19],
            ['name' => 'Phú Bình', 'full_name' => 'Huyện Phú Bình', 'full_name_en' => 'Phu Binh District', 'regions_code' => 19],

            // Các huyện của Lạng Sơn (regions_code = 20)
            ['name' => 'Lạng Sơn', 'full_name' => 'Thành phố Lạng Sơn', 'full_name_en' => 'Lang Son City', 'regions_code' => 20],
            ['name' => 'Tràng Định', 'full_name' => 'Huyện Tràng Định', 'full_name_en' => 'Trang Dinh District', 'regions_code' => 20],
            ['name' => 'Bình Gia', 'full_name' => 'Huyện Bình Gia', 'full_name_en' => 'Binh Gia District', 'regions_code' => 20],
            ['name' => 'Văn Lãng', 'full_name' => 'Huyện Văn Lãng', 'full_name_en' => 'Van Lang District', 'regions_code' => 20],
            ['name' => 'Cao Lộc', 'full_name' => 'Huyện Cao Lộc', 'full_name_en' => 'Cao Loc District', 'regions_code' => 20],
            ['name' => 'Văn Quan', 'full_name' => 'Huyện Văn Quan', 'full_name_en' => 'Van Quan District', 'regions_code' => 20],
            ['name' => 'Bắc Sơn', 'full_name' => 'Huyện Bắc Sơn', 'full_name_en' => 'Bac Son District', 'regions_code' => 20],
            ['name' => 'Hữu Lũng', 'full_name' => 'Huyện Hữu Lũng', 'full_name_en' => 'Huu Lung District', 'regions_code' => 20],
            ['name' => 'Chi Lăng', 'full_name' => 'Huyện Chi Lăng', 'full_name_en' => 'Chi Lang District', 'regions_code' => 20],
            ['name' => 'Lộc Bình', 'full_name' => 'Huyện Lộc Bình', 'full_name_en' => 'Loc Binh District', 'regions_code' => 20],
            ['name' => 'Đình Lập', 'full_name' => 'Huyện Đình Lập', 'full_name_en' => 'Dinh Lap District', 'regions_code' => 20],

            // Các huyện của Quảng Ninh (regions_code = 22)
            ['name' => 'Hạ Long', 'full_name' => 'Thành phố Hạ Long', 'full_name_en' => 'Ha Long City', 'regions_code' => 22],
            ['name' => 'Móng Cái', 'full_name' => 'Thành phố Móng Cái', 'full_name_en' => 'Mong Cai City', 'regions_code' => 22],
            ['name' => 'Cẩm Phả', 'full_name' => 'Thành phố Cẩm Phả', 'full_name_en' => 'Cam Pha City', 'regions_code' => 22],
            ['name' => 'Uông Bí', 'full_name' => 'Thành phố Uông Bí', 'full_name_en' => 'Uong Bi City', 'regions_code' => 22],
            ['name' => 'Bình Liêu', 'full_name' => 'Huyện Bình Liêu', 'full_name_en' => 'Binh Lieu District', 'regions_code' => 22],
            ['name' => 'Tiên Yên', 'full_name' => 'Huyện Tiên Yên', 'full_name_en' => 'Tien Yen District', 'regions_code' => 22],
            ['name' => 'Đầm Hà', 'full_name' => 'Huyện Đầm Hà', 'full_name_en' => 'Dam Ha District', 'regions_code' => 22],
            ['name' => 'Hải Hà', 'full_name' => 'Huyện Hải Hà', 'full_name_en' => 'Hai Ha District', 'regions_code' => 22],
            ['name' => 'Ba Chẽ', 'full_name' => 'Huyện Ba Chẽ', 'full_name_en' => 'Ba Che District', 'regions_code' => 22],
            ['name' => 'Vân Đồn', 'full_name' => 'Huyện Vân Đồn', 'full_name_en' => 'Van Don District', 'regions_code' => 22],
            ['name' => 'Hoành Bồ', 'full_name' => 'Huyện Hoành Bồ', 'full_name_en' => 'Hoanh Bo District', 'regions_code' => 22],
            ['name' => 'Đông Triều', 'full_name' => 'Thị xã Đông Triều', 'full_name_en' => 'Dong Trieu Town', 'regions_code' => 22],
            ['name' => 'Quảng Yên', 'full_name' => 'Thị xã Quảng Yên', 'full_name_en' => 'Quang Yen Town', 'regions_code' => 22],
            ['name' => 'Cô Tô', 'full_name' => 'Huyện Cô Tô', 'full_name_en' => 'Co To District', 'regions_code' => 22],

            // Các huyện của Bắc Giang (regions_code = 24)
            ['name' => 'Bắc Giang', 'full_name' => 'Thành phố Bắc Giang', 'full_name_en' => 'Bac Giang City', 'regions_code' => 24],
            ['name' => 'Yên Thế', 'full_name' => 'Huyện Yên Thế', 'full_name_en' => 'Yen The District', 'regions_code' => 24],
            ['name' => 'Tân Yên', 'full_name' => 'Huyện Tân Yên', 'full_name_en' => 'Tan Yen District', 'regions_code' => 24],
            ['name' => 'Lạng Giang', 'full_name' => 'Huyện Lạng Giang', 'full_name_en' => 'Lang Giang District', 'regions_code' => 24],
            ['name' => 'Lục Nam', 'full_name' => 'Huyện Lục Nam', 'full_name_en' => 'Luc Nam District', 'regions_code' => 24],
            ['name' => 'Lục Ngạn', 'full_name' => 'Huyện Lục Ngạn', 'full_name_en' => 'Luc Ngan District', 'regions_code' => 24],
            ['name' => 'Sơn Động', 'full_name' => 'Huyện Sơn Động', 'full_name_en' => 'Son Dong District', 'regions_code' => 24],
            ['name' => 'Yên Dũng', 'full_name' => 'Huyện Yên Dũng', 'full_name_en' => 'Yen Dung District', 'regions_code' => 24],
            ['name' => 'Việt Yên', 'full_name' => 'Huyện Việt Yên', 'full_name_en' => 'Viet Yen District', 'regions_code' => 24],
            ['name' => 'Hiệp Hòa', 'full_name' => 'Huyện Hiệp Hòa', 'full_name_en' => 'Hiep Hoa District', 'regions_code' => 24],

            // Các huyện của Phú Thọ (regions_code = 25)
            ['name' => 'Việt Trì', 'full_name' => 'Thành phố Việt Trì', 'full_name_en' => 'Viet Tri City', 'regions_code' => 25],
            ['name' => 'Phú Thọ', 'full_name' => 'Thị xã Phú Thọ', 'full_name_en' => 'Phu Tho Town', 'regions_code' => 25],
            ['name' => 'Đoan Hùng', 'full_name' => 'Huyện Đoan Hùng', 'full_name_en' => 'Doan Hung District', 'regions_code' => 25],
            ['name' => 'Hạ Hoà', 'full_name' => 'Huyện Hạ Hoà', 'full_name_en' => 'Ha Hoa District', 'regions_code' => 25],
            ['name' => 'Thanh Ba', 'full_name' => 'Huyện Thanh Ba', 'full_name_en' => 'Thanh Ba District', 'regions_code' => 25],
            ['name' => 'Phù Ninh', 'full_name' => 'Huyện Phù Ninh', 'full_name_en' => 'Phu Ninh District', 'regions_code' => 25],
            ['name' => 'Yên Lập', 'full_name' => 'Huyện Yên Lập', 'full_name_en' => 'Yen Lap District', 'regions_code' => 25],
            ['name' => 'Cẩm Khê', 'full_name' => 'Huyện Cẩm Khê', 'full_name_en' => 'Cam Khe District', 'regions_code' => 25],
            ['name' => 'Tam Nông', 'full_name' => 'Huyện Tam Nông', 'full_name_en' => 'Tam Nong District', 'regions_code' => 25],
            ['name' => 'Lâm Thao', 'full_name' => 'Huyện Lâm Thao', 'full_name_en' => 'Lam Thao District', 'regions_code' => 25],
            ['name' => 'Thanh Sơn', 'full_name' => 'Huyện Thanh Sơn', 'full_name_en' => 'Thanh Son District', 'regions_code' => 25],
            ['name' => 'Thanh Thuỷ', 'full_name' => 'Huyện Thanh Thuỷ', 'full_name_en' => 'Thanh Thuy District', 'regions_code' => 25],
            ['name' => 'Tân Sơn', 'full_name' => 'Huyện Tân Sơn', 'full_name_en' => 'Tan Son District', 'regions_code' => 25],

            // Các huyện của Lào Cai (regions_code = 10)
            ['name' => 'Lào Cai', 'full_name' => 'Thành phố Lào Cai', 'full_name_en' => 'Lao Cai City', 'regions_code' => 10],
            ['name' => 'Bát Xát', 'full_name' => 'Huyện Bát Xát', 'full_name_en' => 'Bat Xat District', 'regions_code' => 10],
            ['name' => 'Mường Khương', 'full_name' => 'Huyện Mường Khương', 'full_name_en' => 'Muong Khuong District', 'regions_code' => 10],
            ['name' => 'Si Ma Cai', 'full_name' => 'Huyện Si Ma Cai', 'full_name_en' => 'Si Ma Cai District', 'regions_code' => 10],
            ['name' => 'Bắc Hà', 'full_name' => 'Huyện Bắc Hà', 'full_name_en' => 'Bac Ha District', 'regions_code' => 10],
            ['name' => 'Bảo Thắng', 'full_name' => 'Huyện Bảo Thắng', 'full_name_en' => 'Bao Thang District', 'regions_code' => 10],
            ['name' => 'Bảo Yên', 'full_name' => 'Huyện Bảo Yên', 'full_name_en' => 'Bao Yen District', 'regions_code' => 10],
            ['name' => 'Sa Pa', 'full_name' => 'Huyện Sa Pa', 'full_name_en' => 'Sa Pa District', 'regions_code' => 10],
            ['name' => 'Văn Bàn', 'full_name' => 'Huyện Văn Bàn', 'full_name_en' => 'Van Ban District', 'regions_code' => 10],

            // Các huyện của Điện Biên (regions_code = 11)
            ['name' => 'Điện Biên Phủ', 'full_name' => 'Thành phố Điện Biên Phủ', 'full_name_en' => 'Dien Bien Phu City', 'regions_code' => 11],
            ['name' => 'Mường Lay', 'full_name' => 'Thị xã Mường Lay', 'full_name_en' => 'Muong Lay Town', 'regions_code' => 11],
            ['name' => 'Mường Nhé', 'full_name' => 'Huyện Mường Nhé', 'full_name_en' => 'Muong Nhe District', 'regions_code' => 11],
            ['name' => 'Mường Chà', 'full_name' => 'Huyện Mường Chà', 'full_name_en' => 'Muong Cha District', 'regions_code' => 11],
            ['name' => 'Tủa Chùa', 'full_name' => 'Huyện Tủa Chùa', 'full_name_en' => 'Tua Chua District', 'regions_code' => 11],
            ['name' => 'Tuần Giáo', 'full_name' => 'Huyện Tuần Giáo', 'full_name_en' => 'Tuan Giao District', 'regions_code' => 11],
            ['name' => 'Điện Biên', 'full_name' => 'Huyện Điện Biên', 'full_name_en' => 'Dien Bien District', 'regions_code' => 11],
            ['name' => 'Điện Biên Đông', 'full_name' => 'Huyện Điện Biên Đông', 'full_name_en' => 'Dien Bien Dong District', 'regions_code' => 11],
            ['name' => 'Mường Ảng', 'full_name' => 'Huyện Mường Ảng', 'full_name_en' => 'Muong Ang District', 'regions_code' => 11],
            ['name' => 'Nậm Pồ', 'full_name' => 'Huyện Nậm Pồ', 'full_name_en' => 'Nam Po District', 'regions_code' => 11],

            // Các huyện của Lai Châu (regions_code = 12)
            ['name' => 'Lai Châu', 'full_name' => 'Thành phố Lai Châu', 'full_name_en' => 'Lai Chau City', 'regions_code' => 12],
            ['name' => 'Tam Đường', 'full_name' => 'Huyện Tam Đường', 'full_name_en' => 'Tam Duong District', 'regions_code' => 12],
            ['name' => 'Mường Tè', 'full_name' => 'Huyện Mường Tè', 'full_name_en' => 'Muong Te District', 'regions_code' => 12],
            ['name' => 'Sìn Hồ', 'full_name' => 'Huyện Sìn Hồ', 'full_name_en' => 'Sin Ho District', 'regions_code' => 12],
            ['name' => 'Phong Thổ', 'full_name' => 'Huyện Phong Thổ', 'full_name_en' => 'Phong Tho District', 'regions_code' => 12],
            ['name' => 'Than Uyên', 'full_name' => 'Huyện Than Uyên', 'full_name_en' => 'Than Uyen District', 'regions_code' => 12],
            ['name' => 'Tân Uyên', 'full_name' => 'Huyện Tân Uyên', 'full_name_en' => 'Tan Uyen District', 'regions_code' => 12],
            ['name' => 'Nậm Nhùn', 'full_name' => 'Huyện Nậm Nhùn', 'full_name_en' => 'Nam Nhun District', 'regions_code' => 12],

            // Các huyện của Sơn La (regions_code = 14)
            ['name' => 'Sơn La', 'full_name' => 'Thành phố Sơn La', 'full_name_en' => 'Son La City', 'regions_code' => 14],
            ['name' => 'Quỳnh Nhai', 'full_name' => 'Huyện Quỳnh Nhai', 'full_name_en' => 'Quynh Nhai District', 'regions_code' => 14],
            ['name' => 'Thuận Châu', 'full_name' => 'Huyện Thuận Châu', 'full_name_en' => 'Thuan Chau District', 'regions_code' => 14],
            ['name' => 'Mường La', 'full_name' => 'Huyện Mường La', 'full_name_en' => 'Muong La District', 'regions_code' => 14],
            ['name' => 'Bắc Yên', 'full_name' => 'Huyện Bắc Yên', 'full_name_en' => 'Bac Yen District', 'regions_code' => 14],
            ['name' => 'Phù Yên', 'full_name' => 'Huyện Phù Yên', 'full_name_en' => 'Phu Yen District', 'regions_code' => 14],
            ['name' => 'Mộc Châu', 'full_name' => 'Huyện Mộc Châu', 'full_name_en' => 'Moc Chau District', 'regions_code' => 14],
            ['name' => 'Yên Châu', 'full_name' => 'Huyện Yên Châu', 'full_name_en' => 'Yen Chau District', 'regions_code' => 14],
            ['name' => 'Mai Sơn', 'full_name' => 'Huyện Mai Sơn', 'full_name_en' => 'Mai Son District', 'regions_code' => 14],
            ['name' => 'Sông Mã', 'full_name' => 'Huyện Sông Mã', 'full_name_en' => 'Song Ma District', 'regions_code' => 14],
            ['name' => 'Sốp Cộp', 'full_name' => 'Huyện Sốp Cộp', 'full_name_en' => 'Sop Cop District', 'regions_code' => 14],
            ['name' => 'Vân Hồ', 'full_name' => 'Huyện Vân Hồ', 'full_name_en' => 'Van Ho District', 'regions_code' => 14],

            // Các huyện của Yên Bái (regions_code = 15)
            ['name' => 'Yên Bái', 'full_name' => 'Thành phố Yên Bái', 'full_name_en' => 'Yen Bai City', 'regions_code' => 15],
            ['name' => 'Nghĩa Lộ', 'full_name' => 'Thị xã Nghĩa Lộ', 'full_name_en' => 'Nghia Lo Town', 'regions_code' => 15],
            ['name' => 'Lục Yên', 'full_name' => 'Huyện Lục Yên', 'full_name_en' => 'Luc Yen District', 'regions_code' => 15],
            ['name' => 'Văn Yên', 'full_name' => 'Huyện Văn Yên', 'full_name_en' => 'Van Yen District', 'regions_code' => 15],
            ['name' => 'Mù Căng Chải', 'full_name' => 'Huyện Mù Căng Chải', 'full_name_en' => 'Mu Cang Chai District', 'regions_code' => 15],
            ['name' => 'Trấn Yên', 'full_name' => 'Huyện Trấn Yên', 'full_name_en' => 'Tran Yen District', 'regions_code' => 15],
            ['name' => 'Trạm Tấu', 'full_name' => 'Huyện Trạm Tấu', 'full_name_en' => 'Tram Tau District', 'regions_code' => 15],
            ['name' => 'Văn Chấn', 'full_name' => 'Huyện Văn Chấn', 'full_name_en' => 'Van Chan District', 'regions_code' => 15],
            ['name' => 'Yên Bình', 'full_name' => 'Huyện Yên Bình', 'full_name_en' => 'Yen Binh District', 'regions_code' => 15],

            // Các huyện của Hoà Bình (regions_code = 17)
            ['name' => 'Hoà Bình', 'full_name' => 'Thành phố Hoà Bình', 'full_name_en' => 'Hoa Binh City', 'regions_code' => 17],
            ['name' => 'Đà Bắc', 'full_name' => 'Huyện Đà Bắc', 'full_name_en' => 'Da Bac District', 'regions_code' => 17],
            ['name' => 'Kỳ Sơn', 'full_name' => 'Huyện Kỳ Sơn', 'full_name_en' => 'Ky Son District', 'regions_code' => 17],
            ['name' => 'Lương Sơn', 'full_name' => 'Huyện Lương Sơn', 'full_name_en' => 'Luong Son District', 'regions_code' => 17],
            ['name' => 'Kim Bôi', 'full_name' => 'Huyện Kim Bôi', 'full_name_en' => 'Kim Boi District', 'regions_code' => 17],
            ['name' => 'Cao Phong', 'full_name' => 'Huyện Cao Phong', 'full_name_en' => 'Cao Phong District', 'regions_code' => 17],
            ['name' => 'Tân Lạc', 'full_name' => 'Huyện Tân Lạc', 'full_name_en' => 'Tan Lac District', 'regions_code' => 17],
            ['name' => 'Mai Châu', 'full_name' => 'Huyện Mai Châu', 'full_name_en' => 'Mai Chau District', 'regions_code' => 17],
            ['name' => 'Lạc Sơn', 'full_name' => 'Huyện Lạc Sơn', 'full_name_en' => 'Lac Son District', 'regions_code' => 17],
            ['name' => 'Yên Thuỷ', 'full_name' => 'Huyện Yên Thuỷ', 'full_name_en' => 'Yen Thuy District', 'regions_code' => 17],
            ['name' => 'Lạc Thuỷ', 'full_name' => 'Huyện Lạc Thuỷ', 'full_name_en' => 'Lac Thuy District', 'regions_code' => 17],

            // Các huyện của Bình Phước (regions_code = 70)
            ['name' => 'Đồng Xoài', 'full_name' => 'Thành phố Đồng Xoài', 'full_name_en' => 'Dong Xoai City', 'regions_code' => 70],
            ['name' => 'Bình Long', 'full_name' => 'Thị xã Bình Long', 'full_name_en' => 'Binh Long Town', 'regions_code' => 70],
            ['name' => 'Phước Long', 'full_name' => 'Thị xã Phước Long', 'full_name_en' => 'Phuoc Long Town', 'regions_code' => 70],
            ['name' => 'Bù Gia Mập', 'full_name' => 'Huyện Bù Gia Mập', 'full_name_en' => 'Bu Gia Map District', 'regions_code' => 70],
            ['name' => 'Lộc Ninh', 'full_name' => 'Huyện Lộc Ninh', 'full_name_en' => 'Loc Ninh District', 'regions_code' => 70],
            ['name' => 'Bù Đốp', 'full_name' => 'Huyện Bù Đốp', 'full_name_en' => 'Bu Dop District', 'regions_code' => 70],
            ['name' => 'Hớn Quản', 'full_name' => 'Huyện Hớn Quản', 'full_name_en' => 'Hon Quan District', 'regions_code' => 70],
            ['name' => 'Đồng Phú', 'full_name' => 'Huyện Đồng Phú', 'full_name_en' => 'Dong Phu District', 'regions_code' => 70],
            ['name' => 'Bù Đăng', 'full_name' => 'Huyện Bù Đăng', 'full_name_en' => 'Bu Dang District', 'regions_code' => 70],
            ['name' => 'Chơn Thành', 'full_name' => 'Huyện Chơn Thành', 'full_name_en' => 'Chon Thanh District', 'regions_code' => 70],
            ['name' => 'Phú Riềng', 'full_name' => 'Huyện Phú Riềng', 'full_name_en' => 'Phu Rieng District', 'regions_code' => 70],

            // Các huyện của Tây Ninh (regions_code = 72)
            ['name' => 'Tây Ninh', 'full_name' => 'Thành phố Tây Ninh', 'full_name_en' => 'Tay Ninh City', 'regions_code' => 72],
            ['name' => 'Tân Biên', 'full_name' => 'Huyện Tân Biên', 'full_name_en' => 'Tan Bien District', 'regions_code' => 72],
            ['name' => 'Tân Châu', 'full_name' => 'Huyện Tân Châu', 'full_name_en' => 'Tan Chau District', 'regions_code' => 72],
            ['name' => 'Dương Minh Châu', 'full_name' => 'Huyện Dương Minh Châu', 'full_name_en' => 'Duong Minh Chau District', 'regions_code' => 72],
            ['name' => 'Châu Thành', 'full_name' => 'Huyện Châu Thành', 'full_name_en' => 'Chau Thanh District', 'regions_code' => 72],
            ['name' => 'Hòa Thành', 'full_name' => 'Thị xã Hòa Thành', 'full_name_en' => 'Hoa Thanh Town', 'regions_code' => 72],
            ['name' => 'Gò Dầu', 'full_name' => 'Huyện Gò Dầu', 'full_name_en' => 'Go Dau District', 'regions_code' => 72],
            ['name' => 'Bến Cầu', 'full_name' => 'Huyện Bến Cầu', 'full_name_en' => 'Ben Cau District', 'regions_code' => 72],
            ['name' => 'Trảng Bàng', 'full_name' => 'Thị xã Trảng Bàng', 'full_name_en' => 'Trang Bang Town', 'regions_code' => 72],

            // Các huyện của Bình Dương (regions_code = 74)
            ['name' => 'Thủ Dầu Một', 'full_name' => 'Thành phố Thủ Dầu Một', 'full_name_en' => 'Thu Dau Mot City', 'regions_code' => 74],
            ['name' => 'Bàu Bàng', 'full_name' => 'Huyện Bàu Bàng', 'full_name_en' => 'Bau Bang District', 'regions_code' => 74],
            ['name' => 'Dầu Tiếng', 'full_name' => 'Huyện Dầu Tiếng', 'full_name_en' => 'Dau Tieng District', 'regions_code' => 74],
            ['name' => 'Bến Cát', 'full_name' => 'Thị xã Bến Cát', 'full_name_en' => 'Ben Cat Town', 'regions_code' => 74],
            ['name' => 'Phú Giáo', 'full_name' => 'Huyện Phú Giáo', 'full_name_en' => 'Phu Giao District', 'regions_code' => 74],
            ['name' => 'Tân Uyên', 'full_name' => 'Thị xã Tân Uyên', 'full_name_en' => 'Tan Uyen Town', 'regions_code' => 74],
            ['name' => 'Dĩ An', 'full_name' => 'Thành phố Dĩ An', 'full_name_en' => 'Di An City', 'regions_code' => 74],
            ['name' => 'Thuận An', 'full_name' => 'Thành phố Thuận An', 'full_name_en' => 'Thuan An City', 'regions_code' => 74],
            ['name' => 'Bắc Tân Uyên', 'full_name' => 'Huyện Bắc Tân Uyên', 'full_name_en' => 'Bac Tan Uyen District', 'regions_code' => 74],

            // Các huyện của Đồng Nai (regions_code = 75)
            ['name' => 'Biên Hòa', 'full_name' => 'Thành phố Biên Hòa', 'full_name_en' => 'Bien Hoa City', 'regions_code' => 75],
            ['name' => 'Long Khánh', 'full_name' => 'Thành phố Long Khánh', 'full_name_en' => 'Long Khanh City', 'regions_code' => 75],
            ['name' => 'Tân Phú', 'full_name' => 'Huyện Tân Phú', 'full_name_en' => 'Tan Phu District', 'regions_code' => 75],
            ['name' => 'Vĩnh Cửu', 'full_name' => 'Huyện Vĩnh Cửu', 'full_name_en' => 'Vinh Cuu District', 'regions_code' => 75],
            ['name' => 'Định Quán', 'full_name' => 'Huyện Định Quán', 'full_name_en' => 'Dinh Quan District', 'regions_code' => 75],
            ['name' => 'Trảng Bom', 'full_name' => 'Huyện Trảng Bom', 'full_name_en' => 'Trang Bom District', 'regions_code' => 75],
            ['name' => 'Thống Nhất', 'full_name' => 'Huyện Thống Nhất', 'full_name_en' => 'Thong Nhat District', 'regions_code' => 75],
            ['name' => 'Cẩm Mỹ', 'full_name' => 'Huyện Cẩm Mỹ', 'full_name_en' => 'Cam My District', 'regions_code' => 75],
            ['name' => 'Long Thành', 'full_name' => 'Huyện Long Thành', 'full_name_en' => 'Long Thanh District', 'regions_code' => 75],
            ['name' => 'Xuân Lộc', 'full_name' => 'Huyện Xuân Lộc', 'full_name_en' => 'Xuan Loc District', 'regions_code' => 75],
            ['name' => 'Nhơn Trạch', 'full_name' => 'Huyện Nhơn Trạch', 'full_name_en' => 'Nhon Trach District', 'regions_code' => 75],

            // Các huyện của Bà Rịa - Vũng Tàu (regions_code = 77)
            ['name' => 'Vũng Tàu', 'full_name' => 'Thành phố Vũng Tàu', 'full_name_en' => 'Vung Tau City', 'regions_code' => 77],
            ['name' => 'Bà Rịa', 'full_name' => 'Thành phố Bà Rịa', 'full_name_en' => 'Ba Ria City', 'regions_code' => 77],
            ['name' => 'Châu Đức', 'full_name' => 'Huyện Châu Đức', 'full_name_en' => 'Chau Duc District', 'regions_code' => 77],
            ['name' => 'Xuyên Mộc', 'full_name' => 'Huyện Xuyên Mộc', 'full_name_en' => 'Xuyen Moc District', 'regions_code' => 77],
            ['name' => 'Long Điền', 'full_name' => 'Huyện Long Điền', 'full_name_en' => 'Long Dien District', 'regions_code' => 77],
            ['name' => 'Đất Đỏ', 'full_name' => 'Huyện Đất Đỏ', 'full_name_en' => 'Dat Do District', 'regions_code' => 77],
            ['name' => 'Tân Thành', 'full_name' => 'Thị xã Phú Mỹ', 'full_name_en' => 'Phu My Town', 'regions_code' => 77],
            ['name' => 'Côn Đảo', 'full_name' => 'Huyện Côn Đảo', 'full_name_en' => 'Con Dao District', 'regions_code' => 77],

            // Các huyện của Nam Định (regions_code = 36)
            ['name' => 'Nam Định', 'full_name' => 'Thành phố Nam Định', 'full_name_en' => 'Nam Dinh City', 'regions_code' => 36],
            ['name' => 'Mỹ Lộc', 'full_name' => 'Huyện Mỹ Lộc', 'full_name_en' => 'My Loc District', 'regions_code' => 36],
            ['name' => 'Vụ Bản', 'full_name' => 'Huyện Vụ Bản', 'full_name_en' => 'Vu Ban District', 'regions_code' => 36],
            ['name' => 'Ý Yên', 'full_name' => 'Huyện Ý Yên', 'full_name_en' => 'Y Yen District', 'regions_code' => 36],
            ['name' => 'Nghĩa Hưng', 'full_name' => 'Huyện Nghĩa Hưng', 'full_name_en' => 'Nghia Hung District', 'regions_code' => 36],
            ['name' => 'Nam Trực', 'full_name' => 'Huyện Nam Trực', 'full_name_en' => 'Nam Truc District', 'regions_code' => 36],
            ['name' => 'Trực Ninh', 'full_name' => 'Huyện Trực Ninh', 'full_name_en' => 'Truc Ninh District', 'regions_code' => 36],
            ['name' => 'Xuân Trường', 'full_name' => 'Huyện Xuân Trường', 'full_name_en' => 'Xuan Truong District', 'regions_code' => 36],
            ['name' => 'Giao Thủy', 'full_name' => 'Huyện Giao Thủy', 'full_name_en' => 'Giao Thuy District', 'regions_code' => 36],
            ['name' => 'Hải Hậu', 'full_name' => 'Huyện Hải Hậu', 'full_name_en' => 'Hai Hau District', 'regions_code' => 36],

            // Các huyện của Ninh Bình (regions_code = 37)
            ['name' => 'Ninh Bình', 'full_name' => 'Thành phố Ninh Bình', 'full_name_en' => 'Ninh Binh City', 'regions_code' => 37],
            ['name' => 'Tam Điệp', 'full_name' => 'Thành phố Tam Điệp', 'full_name_en' => 'Tam Diep City', 'regions_code' => 37],
            ['name' => 'Nho Quan', 'full_name' => 'Huyện Nho Quan', 'full_name_en' => 'Nho Quan District', 'regions_code' => 37],
            ['name' => 'Gia Viễn', 'full_name' => 'Huyện Gia Viễn', 'full_name_en' => 'Gia Vien District', 'regions_code' => 37],
            ['name' => 'Hoa Lư', 'full_name' => 'Huyện Hoa Lư', 'full_name_en' => 'Hoa Lu District', 'regions_code' => 37],
            ['name' => 'Yên Khánh', 'full_name' => 'Huyện Yên Khánh', 'full_name_en' => 'Yen Khanh District', 'regions_code' => 37],
            ['name' => 'Kim Sơn', 'full_name' => 'Huyện Kim Sơn', 'full_name_en' => 'Kim Son District', 'regions_code' => 37],
            ['name' => 'Yên Mô', 'full_name' => 'Huyện Yên Mô', 'full_name_en' => 'Yen Mo District', 'regions_code' => 37],

            // Các huyện của Thanh Hóa (regions_code = 38)
            ['name' => 'Thanh Hóa', 'full_name' => 'Thành phố Thanh Hóa', 'full_name_en' => 'Thanh Hoa City', 'regions_code' => 38],
            ['name' => 'Bỉm Sơn', 'full_name' => 'Thị xã Bỉm Sơn', 'full_name_en' => 'Bim Son Town', 'regions_code' => 38],
            ['name' => 'Sầm Sơn', 'full_name' => 'Thành phố Sầm Sơn', 'full_name_en' => 'Sam Son City', 'regions_code' => 38],
            ['name' => 'Mường Lát', 'full_name' => 'Huyện Mường Lát', 'full_name_en' => 'Muong Lat District', 'regions_code' => 38],
            ['name' => 'Quan Hóa', 'full_name' => 'Huyện Quan Hóa', 'full_name_en' => 'Quan Hoa District', 'regions_code' => 38],
            ['name' => 'Bá Thước', 'full_name' => 'Huyện Bá Thước', 'full_name_en' => 'Ba Thuoc District', 'regions_code' => 38],
            ['name' => 'Quan Sơn', 'full_name' => 'Huyện Quan Sơn', 'full_name_en' => 'Quan Son District', 'regions_code' => 38],
            ['name' => 'Lang Chánh', 'full_name' => 'Huyện Lang Chánh', 'full_name_en' => 'Lang Chanh District', 'regions_code' => 38],
            ['name' => 'Ngọc Lặc', 'full_name' => 'Huyện Ngọc Lặc', 'full_name_en' => 'Ngoc Lac District', 'regions_code' => 38],
            ['name' => 'Cẩm Thủy', 'full_name' => 'Huyện Cẩm Thủy', 'full_name_en' => 'Cam Thuy District', 'regions_code' => 38],
            ['name' => 'Thạch Thành', 'full_name' => 'Huyện Thạch Thành', 'full_name_en' => 'Thach Thanh District', 'regions_code' => 38],
            ['name' => 'Hà Trung', 'full_name' => 'Huyện Hà Trung', 'full_name_en' => 'Ha Trung District', 'regions_code' => 38],
            ['name' => 'Vĩnh Lộc', 'full_name' => 'Huyện Vĩnh Lộc', 'full_name_en' => 'Vinh Loc District', 'regions_code' => 38],
            ['name' => 'Yên Định', 'full_name' => 'Huyện Yên Định', 'full_name_en' => 'Yen Dinh District', 'regions_code' => 38],
            ['name' => 'Thọ Xuân', 'full_name' => 'Huyện Thọ Xuân', 'full_name_en' => 'Tho Xuan District', 'regions_code' => 38],
            ['name' => 'Thường Xuân', 'full_name' => 'Huyện Thường Xuân', 'full_name_en' => 'Thuong Xuan District', 'regions_code' => 38],
            ['name' => 'Triệu Sơn', 'full_name' => 'Huyện Triệu Sơn', 'full_name_en' => 'Trieu Son District', 'regions_code' => 38],
            ['name' => 'Thiệu Hóa', 'full_name' => 'Huyện Thiệu Hóa', 'full_name_en' => 'Thieu Hoa District', 'regions_code' => 38],
            ['name' => 'Hoằng Hóa', 'full_name' => 'Huyện Hoằng Hóa', 'full_name_en' => 'Hoang Hoa District', 'regions_code' => 38],
            ['name' => 'Hậu Lộc', 'full_name' => 'Huyện Hậu Lộc', 'full_name_en' => 'Hau Loc District', 'regions_code' => 38],
            ['name' => 'Nga Sơn', 'full_name' => 'Huyện Nga Sơn', 'full_name_en' => 'Nga Son District', 'regions_code' => 38],
            ['name' => 'Như Xuân', 'full_name' => 'Huyện Như Xuân', 'full_name_en' => 'Nhu Xuan District', 'regions_code' => 38],
            ['name' => 'Như Thanh', 'full_name' => 'Huyện Như Thanh', 'full_name_en' => 'Nhu Thanh District', 'regions_code' => 38],
            ['name' => 'Nông Cống', 'full_name' => 'Huyện Nông Cống', 'full_name_en' => 'Nong Cong District', 'regions_code' => 38],
            ['name' => 'Đông Sơn', 'full_name' => 'Huyện Đông Sơn', 'full_name_en' => 'Dong Son District', 'regions_code' => 38],
            ['name' => 'Quảng Xương', 'full_name' => 'Huyện Quảng Xương', 'full_name_en' => 'Quang Xuong District', 'regions_code' => 38],
            ['name' => 'Tĩnh Gia', 'full_name' => 'Thị xã Nghi Sơn', 'full_name_en' => 'Nghi Son Town', 'regions_code' => 38],

        ]);
    }
}
